-- Combined for a single paste into the Supabase SQL editor: every coach-mode-era migration,
-- in order, from 20260929_0001_coach_mode.sql through 20261015_0001_coach_manual_bookings.sql.
-- Generated by concatenating the real migration files below - not itself a tracked migration.
-- Every piece is safe to run more than once, so this is safe to run even if some already applied.

-- ============================================================
-- source: supabase/migrations/20260929_0001_coach_mode.sql
-- ============================================================
-- 2026-09-29  Coach mode: a WST-certified coach can be booked for a session instead of the
-- back-and-forth of a WhatsApp thread.
--
-- `is_coach` sits on the public profile (not app_metadata) because it has to be readable by
-- other players browsing a profile, not just by the coach's own session. It cannot be granted by
-- the player themselves: a before-update trigger freezes it back to its old value whenever the
-- write comes from an ordinary signed-in client (auth.role() = 'authenticated'), the same way
-- created_at is frozen for matches in 20260920_0001. Granting coach status is a plain
-- `update public.profiles set is_coach = true where id = '...'` run as the project owner (in the
-- SQL editor, or any service-role connection), which is not the 'authenticated' role and so is
-- not frozen - there is no self-serve "become a coach" toggle in the app, on purpose.
--
-- Safe to run more than once.

begin;

alter table public.profiles add column if not exists is_coach boolean not null default false;

create or replace function public.trg_freeze_is_coach()
returns trigger
language plpgsql
as $$
begin
  if auth.role() = 'authenticated' then
    new.is_coach := old.is_coach;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_profiles_freeze_is_coach on public.profiles;
create trigger trg_profiles_freeze_is_coach
before update on public.profiles
for each row execute function public.trg_freeze_is_coach();

-- A window of time a coach has said they can take a session. Open until a booking is made
-- against it; the coach removes it themselves if they no longer want it shown.
create table if not exists public.coach_availability (
  id uuid primary key default gen_random_uuid(),
  coach_id uuid not null references auth.users(id) on delete cascade,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint coach_availability_time_order check (ends_at > starts_at)
);
create index if not exists coach_availability_coach_idx on public.coach_availability (coach_id, starts_at);

-- A player's request for one of those windows, and how the coach answered it.
create table if not exists public.coach_bookings (
  id uuid primary key default gen_random_uuid(),
  coach_id uuid not null references auth.users(id) on delete cascade,
  player_id uuid not null references auth.users(id) on delete cascade,
  availability_id uuid references public.coach_availability(id) on delete set null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status text not null default 'pending',
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint coach_bookings_status_check check (status in ('pending', 'accepted', 'declined', 'cancelled')),
  constraint coach_bookings_time_order check (ends_at > starts_at),
  constraint coach_bookings_note_length check (note is null or char_length(note) <= 300)
);
create index if not exists coach_bookings_coach_idx on public.coach_bookings (coach_id, starts_at);
create index if not exists coach_bookings_player_idx on public.coach_bookings (player_id, starts_at);

-- Only one live request per slot at a time, so two players cannot both book the same hour.
create unique index if not exists coach_bookings_one_active_per_slot
  on public.coach_bookings (availability_id)
  where status in ('pending', 'accepted');

create or replace function public.trg_freeze_booking_parties()
returns trigger
language plpgsql
as $$
begin
  new.coach_id := old.coach_id;
  new.player_id := old.player_id;
  new.availability_id := old.availability_id;
  new.starts_at := old.starts_at;
  new.ends_at := old.ends_at;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_coach_bookings_freeze_parties on public.coach_bookings;
create trigger trg_coach_bookings_freeze_parties
before update on public.coach_bookings
for each row execute function public.trg_freeze_booking_parties();

alter table public.coach_availability enable row level security;
alter table public.coach_bookings enable row level security;

-- Availability: any signed-in player can see a coach's open slots, to book one. Only the coach
-- themselves - and only while flagged as a coach - can create or remove their own.
-- Each is dropped first so this file is actually safe to run more than once, as its header claims -
-- `create policy` has no `if not exists` form, so without the drop a rerun would fail here.
drop policy if exists coach_availability_select on public.coach_availability;
create policy coach_availability_select on public.coach_availability for select
  using (auth.role() = 'authenticated');

drop policy if exists coach_availability_insert on public.coach_availability;
create policy coach_availability_insert on public.coach_availability for insert
  with check (
    auth.uid() = coach_id
    and exists (select 1 from public.profiles p where p.id = coach_id and p.is_coach)
  );

drop policy if exists coach_availability_delete on public.coach_availability;
create policy coach_availability_delete on public.coach_availability for delete
  using (auth.uid() = coach_id);

-- Bookings: the coach and the player involved can both see and update their own booking (the
-- app's own UI is what limits a player to cancelling and a coach to accepting or declining -
-- see trg_freeze_booking_parties above for what a write can never change regardless of the UI).
drop policy if exists coach_bookings_select on public.coach_bookings;
create policy coach_bookings_select on public.coach_bookings for select
  using (auth.uid() = coach_id or auth.uid() = player_id);

-- Superseded by 20261015_0001_coach_manual_bookings.sql, which drops and recreates this same
-- policy to also let a coach insert a booking themselves - left here so this file still leaves a
-- correct (if narrower) policy in place if 20261015 has not run yet.
drop policy if exists coach_bookings_insert on public.coach_bookings;
create policy coach_bookings_insert on public.coach_bookings for insert
  with check (
    auth.uid() = player_id
    and exists (select 1 from public.profiles p where p.id = coach_id and p.is_coach)
  );

drop policy if exists coach_bookings_update on public.coach_bookings;
create policy coach_bookings_update on public.coach_bookings for update
  using (auth.uid() = coach_id or auth.uid() = player_id);

commit;

-- ============================================================
-- source: supabase/migrations/20260930_0001_coach_qualifications.sql
-- ============================================================
-- 2026-09-30  Coach qualifications: what a coach adds to their own listing, so players can see
-- what they are qualified in before booking, and whether they are WPBSA accredited.
--
-- Self-declared, like a bio - not verified against the WPBSA's own records, which is why the app
-- always labels it "self-declared" rather than presenting it as a checked fact. Because of that,
-- these columns follow the normal profiles_update_own policy rather than is_coach's frozen one:
-- a coach editing what they say about themselves is the same trust level as editing their bio.
--
-- Safe to run more than once.

begin;

alter table public.profiles add column if not exists coach_qualifications text[] not null default '{}';
alter table public.profiles add column if not exists wpbsa_accredited boolean not null default false;
alter table public.profiles add column if not exists coach_location text;

-- A CHECK constraint cannot itself contain a subquery, even one that only unnests the row's own
-- array column - so the per-tag length rule below lives in this small immutable function instead.
create or replace function public.qualifications_length_ok(tags text[])
returns boolean
language sql
immutable
as $$
  select coalesce(bool_and(char_length(tag) <= 40), true) from unnest(tags) as tag;
$$;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'profiles_coach_location_length') then
    alter table public.profiles
      add constraint profiles_coach_location_length check (coach_location is null or char_length(coach_location) <= 120);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'profiles_coach_qualifications_count') then
    alter table public.profiles
      add constraint profiles_coach_qualifications_count check (array_length(coach_qualifications, 1) is null or array_length(coach_qualifications, 1) <= 6);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'profiles_coach_qualifications_length') then
    alter table public.profiles
      add constraint profiles_coach_qualifications_length check (public.qualifications_length_ok(coach_qualifications));
  end if;
end $$;

commit;

-- ============================================================
-- source: supabase/migrations/20261001_0001_coach_location_coords.sql
-- ============================================================
-- 2026-10-01  Real coordinates for a coach's location, alongside the free-text place name added in
-- 20260930_0001. Lets "find a coach near me" eventually sort by real distance instead of just
-- text-matching a town name. Populated by the app's own reverse-geocode when a coach taps "Use my
-- current location" - a coach can still type a location by hand and leave these null.
--
-- Same trust level as coach_location itself: self-declared, editable by the coach via the normal
-- profiles_update_own policy, not frozen like is_coach.
--
-- Safe to run more than once.

begin;

alter table public.profiles add column if not exists coach_lat double precision;
alter table public.profiles add column if not exists coach_lng double precision;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'profiles_coach_lat_range') then
    alter table public.profiles
      add constraint profiles_coach_lat_range check (coach_lat is null or coach_lat between -90 and 90);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'profiles_coach_lng_range') then
    alter table public.profiles
      add constraint profiles_coach_lng_range check (coach_lng is null or coach_lng between -180 and 180);
  end if;
end $$;

commit;

-- ============================================================
-- source: supabase/migrations/20261002_0001_coach_session_notes.sql
-- ============================================================
-- 2026-10-02  A coach's own notes on a session: what was covered, and what to focus on next time.
--
-- A separate table, not a column on coach_bookings, because these are private to the coach - the
-- player that booking is with should never be able to read them. coach_bookings itself is
-- selectable by both parties (they both need to see the booking), so a column there would leak
-- through that same policy; a table of its own can be locked to the coach alone.
--
-- Safe to run more than once.

begin;

create table if not exists public.coach_session_notes (
  booking_id uuid primary key references public.coach_bookings(id) on delete cascade,
  coach_id uuid not null references auth.users(id) on delete cascade,
  notes text not null,
  updated_at timestamptz not null default now(),
  constraint coach_session_notes_length check (char_length(notes) <= 2000)
);
create index if not exists coach_session_notes_coach_idx on public.coach_session_notes (coach_id);

alter table public.coach_session_notes enable row level security;

drop policy if exists coach_session_notes_all on public.coach_session_notes;
create policy coach_session_notes_all on public.coach_session_notes for all
  using (auth.uid() = coach_id)
  with check (auth.uid() = coach_id);

commit;

-- ============================================================
-- source: supabase/migrations/20261003_0001_coach_session_routines.sql
-- ============================================================
-- A coach's record of which routines were covered in a session: the routine, the client's score
-- or practice result, and any notes specific to that routine (separate from the general session
-- notes, so several routines in one session can each have their own comment).
--
-- Same privacy shape as coach_session_notes: a separate table, coach-only RLS, because
-- coach_bookings itself is readable by both parties.
--
-- Safe to run more than once.

begin;

create table if not exists public.coach_session_routines (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null references public.coach_bookings(id) on delete cascade,
  coach_id uuid not null references auth.users(id) on delete cascade,
  routine_id text not null,
  routine_name text not null,
  score integer,
  notes text,
  created_at timestamptz not null default now(),
  constraint coach_session_routines_notes_length check (notes is null or char_length(notes) <= 1000)
);
create index if not exists coach_session_routines_booking_idx on public.coach_session_routines (booking_id);
create index if not exists coach_session_routines_coach_idx on public.coach_session_routines (coach_id);

alter table public.coach_session_routines enable row level security;

drop policy if exists coach_session_routines_all on public.coach_session_routines;
create policy coach_session_routines_all on public.coach_session_routines for all
  using (auth.uid() = coach_id)
  with check (auth.uid() = coach_id);

commit;

-- ============================================================
-- source: supabase/migrations/20261004_0001_coach_groups.sql
-- ============================================================
-- Coach client groups: a coach's own group made of their clients, for sharing practice content
-- (a routine video, an image, a PDF) they want everyone in it to see. Deliberately separate from
-- the general community groups feature (public.groups) - this is a broadcast channel from one
-- coach to their own clients, not a social group players run themselves.
--
-- Safe to run more than once.

begin;

create table if not exists public.coach_groups (
  id uuid primary key default gen_random_uuid(),
  coach_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  constraint coach_groups_name_length check (char_length(name) between 1 and 60)
);
create index if not exists coach_groups_coach_idx on public.coach_groups (coach_id);
alter table public.coach_groups enable row level security;

drop policy if exists coach_groups_owner_all on public.coach_groups;
create policy coach_groups_owner_all on public.coach_groups for all
  using (auth.uid() = coach_id)
  with check (auth.uid() = coach_id);

create table if not exists public.coach_group_members (
  group_id uuid not null references public.coach_groups(id) on delete cascade,
  player_id uuid not null references auth.users(id) on delete cascade,
  added_at timestamptz not null default now(),
  primary key (group_id, player_id)
);
alter table public.coach_group_members enable row level security;

drop policy if exists coach_group_members_coach_all on public.coach_group_members;
create policy coach_group_members_coach_all on public.coach_group_members for all
  using (exists (select 1 from public.coach_groups g where g.id = group_id and g.coach_id = auth.uid()))
  with check (exists (select 1 from public.coach_groups g where g.id = group_id and g.coach_id = auth.uid()));

drop policy if exists coach_group_members_self_select on public.coach_group_members;
create policy coach_group_members_self_select on public.coach_group_members for select
  using (player_id = auth.uid());

-- Added now that coach_group_members exists: lets a member (not just the coach) see the group's
-- own row - its name, for instance - not only their membership row.
drop policy if exists coach_groups_member_select on public.coach_groups;
create policy coach_groups_member_select on public.coach_groups for select
  using (exists (
    select 1 from public.coach_group_members m where m.group_id = id and m.player_id = auth.uid()
  ));

create table if not exists public.coach_group_posts (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.coach_groups(id) on delete cascade,
  coach_id uuid not null references auth.users(id) on delete cascade,
  caption text,
  media_path text not null,
  media_type text not null check (media_type in ('image', 'video', 'pdf')),
  created_at timestamptz not null default now(),
  constraint coach_group_posts_caption_length check (caption is null or char_length(caption) <= 500)
);
create index if not exists coach_group_posts_group_idx on public.coach_group_posts (group_id, created_at desc);
alter table public.coach_group_posts enable row level security;

drop policy if exists coach_group_posts_coach_all on public.coach_group_posts;
create policy coach_group_posts_coach_all on public.coach_group_posts for all
  using (auth.uid() = coach_id)
  with check (auth.uid() = coach_id);

drop policy if exists coach_group_posts_member_select on public.coach_group_posts;
create policy coach_group_posts_member_select on public.coach_group_posts for select
  using (exists (
    select 1 from public.coach_group_members m where m.group_id = coach_group_posts.group_id and m.player_id = auth.uid()
  ));

-- A private bucket for the media itself, one folder per group (path: "<group_id>/<file>"), so
-- storage RLS can check group ownership/membership straight from the path.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'coach-group-media',
  'coach-group-media',
  false,
  104857600,
  array['image/jpeg', 'image/png', 'image/heic', 'video/mp4', 'video/quicktime', 'video/x-m4v', 'application/pdf']
)
on conflict (id) do nothing;

drop policy if exists coach_group_media_insert on storage.objects;
create policy coach_group_media_insert on storage.objects for insert
  with check (
    bucket_id = 'coach-group-media'
    and exists (
      select 1 from public.coach_groups g
      where g.id::text = (storage.foldername(name))[1] and g.coach_id = auth.uid()
    )
  );

drop policy if exists coach_group_media_select on storage.objects;
create policy coach_group_media_select on storage.objects for select
  using (
    bucket_id = 'coach-group-media'
    and (
      exists (
        select 1 from public.coach_groups g
        where g.id::text = (storage.foldername(name))[1] and g.coach_id = auth.uid()
      )
      or exists (
        select 1 from public.coach_group_members m
        where m.group_id::text = (storage.foldername(name))[1] and m.player_id = auth.uid()
      )
    )
  );

drop policy if exists coach_group_media_delete on storage.objects;
create policy coach_group_media_delete on storage.objects for delete
  using (
    bucket_id = 'coach-group-media'
    and exists (
      select 1 from public.coach_groups g
      where g.id::text = (storage.foldername(name))[1] and g.coach_id = auth.uid()
    )
  );

commit;

-- ============================================================
-- source: supabase/migrations/20261005_0001_coach_groups_fix_recursion.sql
-- ============================================================
-- Fixes "infinite recursion detected in policy for relation coach_groups" from the previous
-- migration: coach_groups' member-select policy queried coach_group_members, whose owner-all
-- policy queried coach_groups back again, and Postgres re-evaluates each table's RLS on every
-- subquery against it - so the two policies looped forever.
--
-- Fix: two security-definer helper functions do the cross-table checks. Owned by the migration
-- role (which owns both tables), so they run against the tables directly rather than re-entering
-- RLS - the standard way to break this kind of two-table policy cycle.
--
-- Safe to run more than once.

begin;

create or replace function public.is_coach_group_owner(target_group_id uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.coach_groups g where g.id = target_group_id and g.coach_id = auth.uid()
  );
$$;

create or replace function public.is_coach_group_member(target_group_id uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.coach_group_members m where m.group_id = target_group_id and m.player_id = auth.uid()
  );
$$;

revoke all on function public.is_coach_group_owner(uuid) from public, anon;
revoke all on function public.is_coach_group_member(uuid) from public, anon;
grant execute on function public.is_coach_group_owner(uuid) to authenticated;
grant execute on function public.is_coach_group_member(uuid) to authenticated;

drop policy if exists coach_groups_member_select on public.coach_groups;
create policy coach_groups_member_select on public.coach_groups for select
  using (public.is_coach_group_member(id));

drop policy if exists coach_group_members_coach_all on public.coach_group_members;
create policy coach_group_members_coach_all on public.coach_group_members for all
  using (public.is_coach_group_owner(group_id))
  with check (public.is_coach_group_owner(group_id));

drop policy if exists coach_group_posts_member_select on public.coach_group_posts;
create policy coach_group_posts_member_select on public.coach_group_posts for select
  using (public.is_coach_group_member(group_id));

drop policy if exists coach_group_media_insert on storage.objects;
create policy coach_group_media_insert on storage.objects for insert
  with check (bucket_id = 'coach-group-media' and public.is_coach_group_owner(((storage.foldername(name))[1])::uuid));

drop policy if exists coach_group_media_select on storage.objects;
create policy coach_group_media_select on storage.objects for select
  using (
    bucket_id = 'coach-group-media'
    and (
      public.is_coach_group_owner(((storage.foldername(name))[1])::uuid)
      or public.is_coach_group_member(((storage.foldername(name))[1])::uuid)
    )
  );

drop policy if exists coach_group_media_delete on storage.objects;
create policy coach_group_media_delete on storage.objects for delete
  using (bucket_id = 'coach-group-media' and public.is_coach_group_owner(((storage.foldername(name))[1])::uuid));

commit;

-- ============================================================
-- source: supabase/migrations/20261006_0001_coach_realtime.sql
-- ============================================================
-- Coach mode tables were never added to the realtime publication, so a booking's status changing
-- (accepted, declined, cancelled, rescheduled) never reached the other person's phone until they
-- next opened the app. Live sync (src/sync/realtime.ts) already listens for these tables; this is
-- what actually makes Postgres tell it when a row changes.
--
-- Safe to run more than once.

begin;

do $$
declare t text;
begin
  foreach t in array array['coach_bookings', 'coach_availability', 'coach_session_notes', 'coach_session_routines'] loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end
$$;

commit;

-- ============================================================
-- source: supabase/migrations/20261007_0001_coach_reschedule_reason.sql
-- ============================================================
-- An optional note on why a session was moved, shown to whichever side did not make the change -
-- not mandatory, since the actual reason is often just discussed directly between coach and
-- player, but useful when it isn't.
--
-- Safe to run more than once.

begin;

alter table public.coach_bookings add column if not exists reschedule_reason text;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'coach_bookings_reschedule_reason_length') then
    alter table public.coach_bookings add constraint coach_bookings_reschedule_reason_length
      check (reschedule_reason is null or char_length(reschedule_reason) <= 200);
  end if;
end
$$;

commit;

-- ============================================================
-- source: supabase/migrations/20261008_0001_coach_reschedule_response.sql
-- ============================================================
-- Two fixes to rescheduling, found after 20261007 shipped:
--
-- 1. trg_freeze_booking_parties (from 20260929) froze availability_id, starts_at and ends_at on
--    every update, not just coach_id/player_id. That was meant to stop either side tampering with
--    who a booking is between, but it also silently discarded every reschedule: the UPDATE
--    returned success, the trigger just reset the row back to its old time before it was written,
--    so nothing ever appeared to move. Only coach_id/player_id need to stay frozen.
--
-- 2. A reschedule was applied immediately with no confirmation from the other side. Now it puts
--    the booking back to 'pending' and records which side still needs to answer, the same way a
--    fresh request does - the other person has to accept the new time before it is confirmed.
--
-- Safe to run more than once.

begin;

create or replace function public.trg_freeze_booking_parties()
returns trigger
language plpgsql
as $$
begin
  new.coach_id := old.coach_id;
  new.player_id := old.player_id;
  new.updated_at := now();
  return new;
end;
$$;

alter table public.coach_bookings add column if not exists awaiting_response_from text;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'coach_bookings_awaiting_response_check') then
    alter table public.coach_bookings add constraint coach_bookings_awaiting_response_check
      check (awaiting_response_from is null or awaiting_response_from in ('coach', 'player'));
  end if;
end
$$;

-- Existing pending rows predate this column: they are all fresh requests, so the coach is the one
-- who owes an answer.
update public.coach_bookings set awaiting_response_from = 'coach' where status = 'pending' and awaiting_response_from is null;

-- Only the side actually being asked can turn a pending booking into accepted/declined - otherwise
-- the person who proposed a new time could just approve their own proposal. Cancelling (withdrawing
-- or calling off an already-confirmed session) is untouched: either side can always do that.
create or replace function public.trg_guard_booking_response()
returns trigger
language plpgsql
as $$
begin
  if new.status in ('accepted', 'declined')
     and new.status is distinct from old.status
     and old.status = 'pending'
     and old.awaiting_response_from is not null then
    if old.awaiting_response_from = 'coach' and auth.uid() <> old.coach_id then
      raise exception 'Only the coach can respond to this request.';
    elsif old.awaiting_response_from = 'player' and auth.uid() <> old.player_id then
      raise exception 'Only the player can respond to this request.';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_coach_bookings_guard_response on public.coach_bookings;
create trigger trg_coach_bookings_guard_response
before update on public.coach_bookings
for each row execute function public.trg_guard_booking_response();

commit;

-- ============================================================
-- source: supabase/migrations/20261009_0001_coach_bookings_delete.sql
-- ============================================================
-- coach_bookings had select/insert/update policies but no delete policy, so a client-side delete
-- was silently blocked by RLS (no matching policy = no rows affected). This adds the ability to
-- clear old history - a declined or cancelled request, or an accepted session that has already
-- ended - for whichever side of it is doing the tidying. A booking still pending or still to come
-- can never be deleted this way, only cancelled.
--
-- Safe to run more than once.

begin;

drop policy if exists coach_bookings_delete on public.coach_bookings;
create policy coach_bookings_delete on public.coach_bookings for delete
  using (
    (auth.uid() = coach_id or auth.uid() = player_id)
    and (status <> 'accepted' or ends_at < now())
  );

commit;

-- ============================================================
-- source: supabase/migrations/20261010_0001_missing_fk_indexes.sql
-- ============================================================
-- Foreign key columns with no index of their own. Postgres only indexes the referenced side of a
-- foreign key automatically (the parent's primary key) - never the child column that points at it.
-- Without one, two things both cost disk IO: fetching a parent's children by that column (e.g.
-- every fixture in a tournament), and Postgres's own cascade delete, which has to find every
-- matching child row to remove it and does that with a full table scan when there is no index to
-- use instead. As these tables grow with more users, that scan gets slower and heavier every time.
--
-- Purely additive - no behaviour changes, safe to run anytime, safe to run more than once.

begin;

-- listMemberCoachGroups() (now called on every sign-in via coachStore.hydrate, not just when the
-- Coaching tab is opened) queries this by player_id alone. The table's only index is the
-- (group_id, player_id) primary key, which cannot serve a player_id-only lookup - this was a full
-- table scan on every single hydrate, for every player, coach or not.
create index if not exists coach_group_members_player_idx on public.coach_group_members (player_id);

create index if not exists tournament_fixtures_tournament_idx on public.tournament_fixtures (tournament_id);
create index if not exists tournament_fixture_frames_fixture_idx on public.tournament_fixture_frames (fixture_id);
create index if not exists session_log_results_log_idx on public.session_log_results (log_id);

-- The existing (user_id, match_id, frame_number) index has match_id in the middle, not leading, so
-- it cannot serve a match_id-only lookup either - exactly what deleting a match needs to find its
-- frames to cascade to.
create index if not exists match_frames_match_idx on public.match_frames (match_id);

commit;

-- ============================================================
-- source: supabase/migrations/20261011_0001_coach_gallery.sql
-- ============================================================
-- A coach's own photo gallery - work with professionals, at events, whatever they want a
-- prospective client to see before booking. Shown on the coach profile a player reaches from Find
-- a Coach, so it is readable by anyone signed in, the same visibility as the rest of a coach's
-- public listing (coach_availability, coach_groups). Capped at 6 photos - a gallery, not a feed.
--
-- Safe to run more than once.

begin;

create table if not exists public.coach_gallery_photos (
  id uuid primary key default gen_random_uuid(),
  coach_id uuid not null references auth.users(id) on delete cascade,
  path text not null,
  created_at timestamptz not null default now()
);
create index if not exists coach_gallery_photos_coach_idx on public.coach_gallery_photos (coach_id, created_at);
alter table public.coach_gallery_photos enable row level security;

drop policy if exists coach_gallery_photos_select on public.coach_gallery_photos;
create policy coach_gallery_photos_select on public.coach_gallery_photos for select
  using (auth.role() = 'authenticated');

drop policy if exists coach_gallery_photos_coach_all on public.coach_gallery_photos;
create policy coach_gallery_photos_coach_all on public.coach_gallery_photos for all
  using (
    auth.uid() = coach_id
    and exists (select 1 from public.profiles p where p.id = coach_id and p.is_coach)
  )
  with check (
    auth.uid() = coach_id
    and exists (select 1 from public.profiles p where p.id = coach_id and p.is_coach)
  );

create or replace function public.trg_coach_gallery_limit()
returns trigger
language plpgsql
as $$
begin
  if (select count(*) from public.coach_gallery_photos where coach_id = new.coach_id) >= 6 then
    raise exception 'A coach gallery can hold at most 6 photos.' using errcode = 'P0001';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_coach_gallery_photos_limit on public.coach_gallery_photos;
create trigger trg_coach_gallery_photos_limit
before insert on public.coach_gallery_photos
for each row execute function public.trg_coach_gallery_limit();

-- A public bucket, one folder per coach (path "<coach_id>/<file>") - a player browsing coaches
-- needs to see these without signing anything, unlike the private coach-group-media bucket.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'coach-gallery-photos',
  'coach-gallery-photos',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/heic', 'image/webp']
)
on conflict (id) do nothing;

drop policy if exists coach_gallery_media_insert on storage.objects;
create policy coach_gallery_media_insert on storage.objects for insert
  with check (
    bucket_id = 'coach-gallery-photos'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists coach_gallery_media_select on storage.objects;
create policy coach_gallery_media_select on storage.objects for select
  using (bucket_id = 'coach-gallery-photos');

drop policy if exists coach_gallery_media_delete on storage.objects;
create policy coach_gallery_media_delete on storage.objects for delete
  using (
    bucket_id = 'coach-gallery-photos'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

commit;

-- ============================================================
-- source: supabase/migrations/20261012_0001_profile_images_bucket.sql
-- ============================================================
-- profile-images was documented as a manual setup step (see README.md's "Database Setup") but was
-- never actually finished with the RLS policies a real upload needs - unlike coach-group-media,
-- which has always had its bucket and policies in a migration. authStore.uploadProfilePhoto called
-- this bucket from day one, but nothing in the app actually called that function until
-- AvatarPickerScreen's "Add a photo" was wired up, so the gap went unnoticed: every upload was
-- rejected by storage RLS with no policy to allow it, which surfaced to the player as a generic
-- "check your connection" error instead of the real cause.
--
-- Public, like coach-gallery-photos: a profile photo needs to be visible to anyone viewing that
-- player's profile (CommunityAvatar, headers, coach profiles), with no separate signing step.
--
-- Safe to run more than once.

begin;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'profile-images',
  'profile-images',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/heic', 'image/webp']
)
on conflict (id) do nothing;

-- Path is "<user_id>/avatar-<timestamp>.<ext>" (see authStore.uploadProfilePhoto), so folder name
-- is the same ownership check coach-gallery-photos and coach-group-media already use.
drop policy if exists profile_images_insert on storage.objects;
create policy profile_images_insert on storage.objects for insert
  with check (
    bucket_id = 'profile-images'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists profile_images_select on storage.objects;
create policy profile_images_select on storage.objects for select
  using (bucket_id = 'profile-images');

-- uploadProfilePhoto passes upsert: true, which needs an update policy for the case where it
-- overwrites an existing object rather than inserting a new one.
drop policy if exists profile_images_update on storage.objects;
create policy profile_images_update on storage.objects for update
  using (bucket_id = 'profile-images' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'profile-images' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists profile_images_delete on storage.objects;
create policy profile_images_delete on storage.objects for delete
  using (bucket_id = 'profile-images' and (storage.foldername(name))[1] = auth.uid()::text);

commit;

-- ============================================================
-- source: supabase/migrations/20261013_0001_chat_media.sql
-- ============================================================
-- Sending an image, video or PDF in a chat - direct or group, same as coach group posts, but from
-- either side of a conversation rather than only a coach broadcasting to a group. Reuses the
-- existing 'media' pattern from coach group posts (a new message kind, payload holds the path and
-- type) and the same can_read_conversation()/can_post_conversation() functions chat already uses,
-- so a media message follows exactly the same visibility and posting rules as a text one.
--
-- Safe to run more than once.

begin;

-- Finds the existing check constraint on kind by what it actually checks rather than guessing the
-- name Postgres auto-generated for it, so this doesn't silently no-op if that guess were wrong.
do $$
declare rec record;
begin
  for rec in
    select conname from pg_constraint
    where conrelid = 'public.messages'::regclass and contype = 'c' and pg_get_constraintdef(oid) ilike '%kind%'
  loop
    execute format('alter table public.messages drop constraint %I', rec.conname);
  end loop;
end $$;

alter table public.messages add constraint messages_kind_check check (kind in ('text', 'routine', 'match', 'media'));

-- A private bucket, one folder per conversation (path "<conversation_id>/<file>"), so storage RLS
-- can check conversation access straight from the path the same way coach-group-media does.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'chat-media',
  'chat-media',
  false,
  104857600,
  array['image/jpeg', 'image/png', 'image/heic', 'image/webp', 'video/mp4', 'video/quicktime', 'video/x-m4v', 'application/pdf']
)
on conflict (id) do nothing;

drop policy if exists chat_media_insert on storage.objects;
create policy chat_media_insert on storage.objects for insert
  with check (
    bucket_id = 'chat-media'
    and public.can_post_conversation((storage.foldername(name))[1]::uuid, auth.uid())
  );

drop policy if exists chat_media_select on storage.objects;
create policy chat_media_select on storage.objects for select
  using (
    bucket_id = 'chat-media'
    and public.can_read_conversation((storage.foldername(name))[1]::uuid, auth.uid())
  );

commit;

-- ============================================================
-- source: supabase/migrations/20261013_0002_group_post_filename.sql
-- ============================================================
-- A group post's media_path is a randomised storage key ("<groupId>/<timestamp>-<random>.<ext>"),
-- so the original filename a coach picked (e.g. "Week 3 Safety Drills.pdf") was never kept - every
-- PDF post just showed the generic "Open document" with no way to tell them apart. Keeping the
-- original name lets a post fall back to something meaningful when the coach has not typed their
-- own caption.
--
-- Safe to run more than once.

begin;

alter table public.coach_group_posts add column if not exists file_name text;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'coach_group_posts_file_name_length') then
    alter table public.coach_group_posts
      add constraint coach_group_posts_file_name_length check (file_name is null or char_length(file_name) <= 150);
  end if;
end $$;

commit;

-- ============================================================
-- source: supabase/migrations/20261014_0001_coach_group_posts_realtime.sql
-- ============================================================
-- Coach group posts were never added to the realtime publication, the same gap 20261006 fixed for
-- bookings and availability - a player never found out a coach had posted something new until they
-- next opened the app and happened to check that group.
--
-- Safe to run more than once.

begin;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'coach_group_posts'
  ) then
    execute 'alter publication supabase_realtime add table public.coach_group_posts';
  end if;
end
$$;

commit;

-- ============================================================
-- source: supabase/migrations/20261015_0001_coach_manual_bookings.sql
-- ============================================================
-- A coach's calendar works like a diary, not just an inbox of requests: they can book a slot
-- straight into their own calendar for an existing client, or for someone with no Snookered
-- account at all - a guest_name stands in for player_id in that case.
--
-- Safe to run more than once.

begin;

alter table public.coach_bookings alter column player_id drop not null;
alter table public.coach_bookings add column if not exists guest_name text;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'coach_bookings_guest_name_length') then
    alter table public.coach_bookings add constraint coach_bookings_guest_name_length
      check (guest_name is null or char_length(guest_name) <= 80);
  end if;
end
$$;

-- Exactly one of a real player or a named guest - never both, never neither.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'coach_bookings_player_xor_guest') then
    alter table public.coach_bookings add constraint coach_bookings_player_xor_guest
      check ((player_id is not null) <> (guest_name is not null));
  end if;
end
$$;

-- A coach can now create the row themselves too - for a guest, or for an existing client they are
-- booking straight into their diary - not just a player booking themselves in.
drop policy if exists coach_bookings_insert on public.coach_bookings;
create policy coach_bookings_insert on public.coach_bookings for insert
  with check (
    exists (select 1 from public.profiles p where p.id = coach_id and p.is_coach)
    and (auth.uid() = player_id or auth.uid() = coach_id)
  );

commit;

