import { Routine, RoutineCategory } from "../types";
import { getYoutubeWatchUrl } from "../utils/youtube";
import { EXTRA_CATEGORIES, EXTRA_ROUTINES } from "./routineDrills";
import { FIRST_WAVE_DIAGRAMS } from "./routineDiagrams";

type VideoMeta = {
  id: string;
  title: string;
  channel: string;
};

const now = new Date().toISOString();

const withYouTube = (primary: VideoMeta, alternate?: VideoMeta) => ({
  youtube_video_id: primary.id,
  youtube_url: getYoutubeWatchUrl(primary.id),
  youtube_title: primary.title,
  youtube_channel: primary.channel,
  youtube_alt_video_id: alternate?.id,
  youtube_alt_url: alternate ? getYoutubeWatchUrl(alternate.id) : undefined,
  youtube_alt_title: alternate?.title,
  youtube_alt_channel: alternate?.channel,
});

export const DEFAULT_CATEGORIES: RoutineCategory[] = [
  {
    id: "cat-basics",
    name: "Fundamentals Library",
    description: "Detailed technique guides on grip, stance, bridge, cue action and aiming. Use them as building blocks, then adapt for your own body and natural cueing style.",
    icon: "🎯",
    color: "#0F766E",
    order_index: 1,
    created_at: now,
  },
  {
    id: "cat-break-building",
    name: "Break Building & Colours",
    description: "Pattern drills and colour-clearance routines for building scoring visits.",
    icon: "🔥",
    color: "#B45309",
    order_index: 2,
    created_at: now,
  },
  {
    id: "cat-safety",
    name: "Safety & Escapes",
    description: "Containment, snookers and escape routines for tactical control.",
    icon: "🛡️",
    color: "#1D4ED8",
    order_index: 3,
    created_at: now,
  },
  {
    id: "cat-straight-cueing",
    name: "Cue Delivery & Straight Cueing",
    description: "Straight cueing, strike quality, and delivery consistency drills.",
    icon: "🎱",
    color: "#334155",
    order_index: 4,
    created_at: now,
  },
  {
    id: "cat-cue-ball-control",
    name: "Cue Ball Control & Spin",
    description: "Stun, screw, follow, and side drills for precise position play.",
    icon: "📈",
    color: "#7C3AED",
    order_index: 5,
    created_at: now,
  },
  {
    id: "cat-long-potting",
    name: "Long Potting & Starters",
    description: "Distance potting and opening-red confidence from match-like positions.",
    icon: "🏆",
    color: "#BE123C",
    order_index: 6,
    created_at: now,
  },
  ...EXTRA_CATEGORIES,
];

const ROUTINE_LIST: Routine[] = [
  {
    id: "routine-bridge-grip-stance",
    category_id: "cat-basics",
    name: "Stance and Balance Basics",
    icon: "🧍",
    content_type: "guide",
    difficulty: "beginner",
    summary: "Build a stable stance first, because balance and head stillness decide whether your cue can deliver straight.",
    description:
      "Your stance is the platform for every shot. If balance shifts during delivery, the cue path usually shifts with it and you get thin or thick misses, especially under pressure. This guide explains the core principles used by top players, while reminding you that exact foot position can vary by height, flexibility and comfort.",
    setup_instructions:
      "Set up mostly easy straight and slight-angle pots so you can focus on body mechanics. The goal is not hard potting; it is learning a repeatable address position you can trust in match conditions.",
    steps: [
      "Set your feet before you bend down, and feel your weight balanced and supported, not stretched or unstable.",
      "Choose the shot line while standing, then lower onto that line without twisting your shoulders or hips at the last second.",
      "Keep your head and chest quiet through impact and hold the finish long enough to check if you stayed still.",
      "If you feel strain in your lower back, neck or bridge arm, make small comfort adjustments and retest. Comfortable mechanics are easier to repeat.",
    ],
    success_criteria:
      "Over 20-30 shots, your setup should look similar each time, with minimal movement in head and torso. If misses happen, they should be easier to diagnose because your body is no longer changing between shots.",
    improves: ["Shot stability", "Body alignment", "Composure under pressure", "Repeatable setup"],
    scoring_type: "count",
    estimated_duration_minutes: 15,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "olOV1TVMqtI",
        title: "The Stance",
        channel: "Shaun Murphy Snooker",
      },
      {
        id: "pOWMCJLlQxc",
        title: "The SNOOKER SETUP | Important Details",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-pre-shot-routine",
    category_id: "cat-basics",
    name: "Grip Fundamentals",
    icon: "✋",
    content_type: "guide",
    difficulty: "beginner",
    summary: "Build a pressure-aware grip that stays relaxed in feathering but still delivers a positive strike.",
    description:
      "Grip pressure has a huge effect on cue freedom and timing. Too tight and the arm locks, steering the cue and killing smooth acceleration. Too loose and the cue can wobble at transition, especially on power shots. This guide blends classic fundamentals with modern coaching ideas: start with a soft hold, then allow a natural squeeze through impact without strangling the cue.",
    setup_instructions:
      "Use one repeat pot at short and medium distance. Keep the shot constant and only vary grip pressure so you can feel how timing and cue path change.",
    steps: [
      "Start with a light hold in your back fingers and keep forearm/wrist free during feathering.",
      "On delivery, allow a natural tightening only as the cue passes the cue-ball. Do not clamp early.",
      "Test three pressures on the same shot (light, medium, firm) and log which gives the straightest cue path.",
      "On power shots, increase control gradually while still keeping the arm flowing, not rigid.",
    ],
    success_criteria:
      "Across 20-30 shots, your cue action should stay smooth with fewer jabbed deliveries and less accidental side spin. Your best pressure level should feel repeatable, not forced.",
    improves: ["Grip control", "Cue freedom", "Strike timing", "Delivery stability"],
    scoring_type: "count",
    estimated_duration_minutes: 15,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "b3so08CEOAo",
        title: "Snooker Grip Fundamentals",
        channel: "SnookerLab",
      },
      {
        id: "9r4Tllvo8l8",
        title: "Grip Alternative Guide",
        channel: "SnookerLab",
      }
    ),
  },
  {
    id: "routine-bridge-fundamentals",
    category_id: "cat-basics",
    name: "Bridge Fundamentals",
    icon: "🫱",
    content_type: "guide",
    difficulty: "beginner",
    summary: "Learn stable bridge construction, then adapt open, closed and specialist bridges to shot demands.",
    description:
      "A solid bridge is the cue's support point. If it moves, your tip line moves. This guide covers the most widely taught bridge principles from both traditional coaching and modern online instruction: anchored finger pads, a clear cue channel, and shape changes for screw, cushion shots, shots over balls, and rest work.",
    setup_instructions:
      "Use one repeat pot and one along-cushion pot. Practise open bridge, closed bridge, cushion bridge, and raised bridge over an object ball while keeping the same cueing rhythm.",
    steps: [
      "Form a standard open bridge: spread fingers, plant finger pads, and create a straight cue groove.",
      "Build a closed bridge for extra cue guidance on power or side shots where stability is harder.",
      "For screw shots, lower bridge height while preserving firmness and a clear cue path.",
      "For cushion, over-ball, and awkward reach shots, adapt shape but protect the same core principle: no bridge wobble through impact.",
    ],
    success_criteria:
      "Across mixed bridge types, your hand remains planted and cue remains centred through delivery. You should feel confident switching bridge style without losing strike quality.",
    improves: ["Bridge stability", "Shot adaptability", "Cue guidance", "Awkward-shot confidence"],
    scoring_type: "count",
    estimated_duration_minutes: 16,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "jgysxTFjULE",
        title: "The Bridge",
        channel: "Shaun Murphy Snooker",
      },
      {
        id: "rxSg2ciaV8A",
        title: "The Perfect Bridge Hand Position",
        channel: "Stephen Hendry's Cue Tips",
      }
    ),
  },
  {
    id: "routine-rest-shot-fundamentals",
    category_id: "cat-basics",
    name: "Alignment and Sighting Basics",
    icon: "👁️",
    content_type: "guide",
    difficulty: "beginner",
    summary: "Train your eyes to choose the shot line early and stay with it, because late visual changes are a common reason for misses.",
    description:
      "Good sighting links planning and execution. If you get down before deciding the true contact point, your brain tends to make rushed corrections during the cue action. That leads to steering, deceleration and inconsistent potting. This guide teaches a consistent visual process while allowing room for individual differences in dominant eye and address style.",
    setup_instructions:
      "Use straight, half-ball and three-quarter-ball examples. Calling these angles before each shot improves judgement and makes aiming errors easier to classify.",
    steps: [
      "Stand directly behind the shot line and decide the intended contact point before approaching the table.",
      "Step into stance with cue, forearm and intended line connected; avoid walking in from the side and correcting late.",
      "Keep your final visual routine consistent so your trigger point and timing become automatic.",
      "If you miss, label it clearly as thick, thin or pace-related rather than guessing. Honest feedback speeds improvement.",
    ],
    success_criteria:
      "You can call contact thickness before each shot and stay with that decision through delivery. Misses should become more predictable rather than random.",
    improves: ["Aiming clarity", "Shot-line discipline", "Visual routine", "Decision confidence"],
    scoring_type: "percentage",
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "CJHVs0SN4jI",
        title: "A Dummies Guide to Sighting",
        channel: "Shaun Murphy Snooker",
      },
      {
        id: "nSVc5gvvlmc",
        title: "08. Aiming in Snooker - Where should you look?",
        channel: "Barry Stark Snooker Coach",
      }
    ),
  },
  {
    id: "routine-potting-fundamentals",
    category_id: "cat-basics",
    name: "Cueing Action and Potting Basics",
    icon: "🎯",
    content_type: "guide",
    difficulty: "beginner",
    summary: "Develop a repeatable cue action with clear rhythm, pause and follow-through so pressure does not break your timing.",
    description:
      "Cue action is where fundamentals meet the cue ball. Many misses come from rushing the transition, jabbing at impact, or pulling out of the shot too early. This guide builds timing in stages. The exact tempo can be personal, but the principles of smooth acceleration, stable head position and complete follow-through remain essential.",
    setup_instructions:
      "Start with plain-ball pots to confirm strike quality. Add gentle stun and screw only when the basic cue action remains stable and repeatable.",
    steps: [
      "Use the same routine each time: settle, feather, pause, deliver. Consistent timing removes guesswork.",
      "Let the cue accelerate through the cue ball rather than stabbing at it. The cue should finish naturally down the line.",
      "Hold your finish to verify head stillness and cue direction before looking up.",
      "When results dip, return to simple plain-ball shots to rebuild timing before adding spin again.",
    ],
    success_criteria:
      "Across 20+ shots, cue path and finish should look consistent. You should feel less rushed and see fewer misses caused by tension, steering or deceleration.",
    improves: ["Cue timing", "Strike quality", "Potting consistency", "Self-correction"],
    scoring_type: "count",
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "Tr0Olz9qnDo",
        title: "Cue Action and Follow Through",
        channel: "Barry Stark Snooker Coach",
      },
      {
        id: "ilS_YOUpf9s",
        title: "Snooker Aiming Fundamentals",
        channel: "SnookerLab",
      }
    ),
  },
  {
    id: "routine-head-position-fundamentals",
    category_id: "cat-basics",
    name: "Head Position Fundamentals",
    icon: "🧠",
    content_type: "guide",
    difficulty: "beginner",
    summary: "Learn consistent head placement so your eye line and cue line stay connected from setup to strike.",
    description:
      "Head position is one of the biggest hidden causes of inconsistency. If head height, chin distance, or eye alignment changes shot to shot, players misread angles and start steering the cue. This guide teaches a repeatable head position with room for dominant-eye and body-type variations.",
    setup_instructions:
      "Use straight and slight-angle pots. Keep cue-ball and object-ball positions simple so you can focus on head placement, not shot difficulty.",
    steps: [
      "Set your feet and bridge first, then lower head into final position instead of dropping head early.",
      "Bring chin close to cue only as far as comfortable. Avoid forcing your neck lower than your flexibility allows.",
      "Check that eyes feel level and quiet at address, with cue running naturally beneath your visual line.",
      "Hold still after contact and verify whether head moved before or during strike.",
    ],
    success_criteria:
      "Across 20-30 shots, head height and cue-under-chin relationship should look repeatable and misses should become easier to classify.",
    improves: ["Visual consistency", "Cue-line trust", "Aiming stability"],
    scoring_type: "count",
    estimated_duration_minutes: 14,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "EtMpcY6aJEU",
        title: "Head Position and Stability",
        channel: "Barry Stark Snooker Coach",
      },
      {
        id: "1m1Xv-DX7z8",
        title: "Snooker Head Position Alternative",
        channel: "SnookerLab",
      }
    ),
  },
  {
    id: "routine-straight-cueing-fundamentals-guide",
    category_id: "cat-basics",
    name: "Straight Cueing Fundamentals",
    icon: "📏",
    content_type: "guide",
    difficulty: "beginner",
    summary: "Build a cue path that stays true on the line, especially on simple shots where errors are exposed.",
    description:
      "Straight cueing is a base skill that supports aiming, spin control, and pace control. If the cue wanders left/right, even perfect aiming decisions break down. This guide explains how to check cue straightness and remove common steering habits.",
    setup_instructions:
      "Use straight pots and line drills. Begin close and only increase distance when cue path remains clean.",
    steps: [
      "Set up centre-ball strikes on straight pots to remove spin variables.",
      "Watch cue travel in and out of the bridge channel during feathers and final delivery.",
      "Track miss pattern: cut too thin can indicate one side bias; cut too thick can indicate the opposite.",
      "Use slow-motion video from rear line to confirm whether cue tracks straight through strike.",
    ],
    success_criteria:
      "On a block of straight pots, you should see tighter potting pattern and reduced left/right miss bias.",
    improves: ["Cue-line consistency", "Centre-ball contact", "Diagnostic awareness"],
    scoring_type: "count",
    estimated_duration_minutes: 16,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "UZeeYTCXlhI",
        title: "Snooker Mindset For STRAIGHT CUEING",
        channel: "BartonSnooker",
      },
      {
        id: "dQnL-Ot7jXA",
        title: "Snooker Straight Cueing How To Practice",
        channel: "Break from life",
      }
    ),
  },
  {
    id: "routine-cue-ball-control-fundamentals-guide",
    category_id: "cat-basics",
    name: "Cue Ball Control Fundamentals",
    icon: "⚪",
    content_type: "guide",
    difficulty: "beginner",
    summary: "Understand basic cue-ball reactions from simple tip positions before advanced positional play.",
    description:
      "Cue-ball control starts with predictable contact, not complicated patterns. Players improve faster when they master plain-ball, follow, stun, and screw on short controlled shots first. This guide builds those basics in a clear progression.",
    setup_instructions:
      "Use one object-ball position and play repeated shots with clear tip-height intentions: centre, above centre, below centre.",
    steps: [
      "Play plain-ball shots first and observe natural cue-ball path after contact.",
      "Add slight follow and note how far the cue-ball runs through at the same cue speed.",
      "Add slight backspin and note return distance at same cue speed.",
      "Record outcomes and keep stroke speed as constant as possible to isolate strike point effects.",
    ],
    success_criteria:
      "You can predict cue-ball finish zones with reasonable accuracy on plain, follow, and screw basics.",
    improves: ["Position awareness", "Tip-height control", "Pace-strike relationship"],
    scoring_type: "count",
    estimated_duration_minutes: 16,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "FdiKPwMl_0M",
        title: "Snooker Cue Ball Control Fundamentals",
        channel: "SnookerLab",
      },
      {
        id: "Zz6Afney-fo",
        title: "Cue Ball Control Alternative Guide",
        channel: "SnookerLab",
      }
    ),
  },
  {
    id: "routine-pre-shot-system-fundamentals",
    category_id: "cat-basics",
    name: "Pre-Shot Routine Fundamentals",
    icon: "🧭",
    content_type: "guide",
    difficulty: "beginner",
    summary: "Create a repeatable pre-shot routine so decision, setup, and delivery happen in a stable sequence.",
    description:
      "A pre-shot routine is the bridge between tactical choice and technical execution. Without structure, players rush hard shots and overthink easy shots. This guide teaches a simple repeatable sequence that can be used in both practice and match play.",
    setup_instructions:
      "Run this guide on easy-to-medium pots first. The goal is consistency of routine, not shot difficulty.",
    steps: [
      "Behind shot: choose the shot intention, contact point, and intended cue-ball path.",
      "Walk-in: approach along shot line and set feet with balance before lowering.",
      "Settle: build bridge, cue on line, and run purposeful feathers.",
      "Deliver: pause and play the shot without changing the decision at the last second.",
    ],
    success_criteria:
      "Your routine order stays consistent across different shots, and hesitation or last-second changes reduce over time.",
    improves: ["Decision clarity", "Shot conviction", "Match composure"],
    scoring_type: "count",
    estimated_duration_minutes: 15,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "_JpwKrzVcL4",
        title: "Snooker Pre-Shot Routine Fundamentals",
        channel: "SnookerLab",
      },
      {
        id: "fi8JnUlmhwA",
        title: "Pre-Shot Routine Alternative Guide",
        channel: "SnookerLab",
      }
    ),
  },
  {
    id: "routine-line-up",
    category_id: "cat-break-building",
    name: "The Snooker Line Up",
    icon: "🔥",
    difficulty: "intermediate",
    summary: "Classic 15-red line-up to build break rhythm and positional discipline.",
    description: "Use a full line of reds through the middle of the table to train break-building patterns with all colours on their spots.",
    setup_instructions: "Place all colours on their spots. Set 15 reds in a straight central line: 2 behind the black (between the black spot and the top cushion), 4 between the black and pink, 7 between the pink and blue, and 2 between the blue and brown. Start from a chosen red, often the second red down from the black.",
    steps: ["Choose a consistent starting red and use it each visit so your scoring is comparable.", "Pot red then colour while keeping the cue-ball in the open and away from cushions where possible.", "If the break ends, reset the line-up and record the break or the number of reds cleared."],
    success_criteria: "Log your best visit out of 147, then track your average break across 5 visits.",
    improves: ["Break continuity", "Angle management", "Recovery choices"],
    scoring_type: "points",
    max_score: 147,
    estimated_duration_minutes: 30,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "3CKs5pmfss4",
        title: "The Line Up",
        channel: "Shaun Murphy Snooker",
      },
      {
        id: "vv2Wjdf3wl8",
        title: "Snooker Line-Up Tutorial - Snooker Lesson",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-t-routine",
    category_id: "cat-break-building",
    name: "The Snooker T Line Up",
    icon: "📐",
    difficulty: "advanced",
    summary: "Advanced T-shape break-building routine for close-control cue-ball work.",
    description: "The T Line-Up tests break-building around the pink area, with little room for error in angle and pace.",
    setup_instructions: "Place all colours on their spots. Set 15 reds in a T shape: reds spread left and right from the pink line, with a central stem running down towards the black.",
    steps: ["Start from a chosen red with the cue-ball in open space near the T formation.", "Alternate red and colour while keeping the cue-ball under tight control around the T.", "If you miss, reset and track either break score or reds remaining for comparison."],
    success_criteria: "Log your best visit out of 147, then note completed T clearances and controlled visits in 30 minutes.",
    improves: ["Pattern planning", "Cue-ball control", "Break discipline"],
    scoring_type: "points",
    max_score: 147,
    estimated_duration_minutes: 30,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "oU3-Cl-N59I",
        title: "Snooker T Practice Routine",
        channel: "Barry Stark Snooker Coach",
      },
      {
        id: "CjBAH5FV4EM",
        title: "Snooker T Exercise - Discipline & Consistency",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-around-colours",
    category_id: "cat-break-building",
    name: "Mastering The Colours",
    icon: "🌈",
    difficulty: "intermediate",
    summary: "Colour-clearance routine for cue-ball touch and end-of-frame planning.",
    description: "Clear the colours in order while keeping the cue-ball under close control from ball to ball.",
    setup_instructions: "Place all colours on their spots and start with the cue-ball in hand in the D.",
    steps: ["Call the intended cue-ball path before each colour.", "Use controlled pace so recovery shots stay simple.", "Restart the clearance after any miss or poor position."],
    success_criteria: "Number of full colour clearances completed in 20 minutes.",
    improves: ["Touch", "Colour-clearance planning", "Frame finishing"],
    scoring_type: "count",
    max_score: 10,
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "NaWnabDwkEU",
        title: "SNOOKER Colours Clearance | HEADCAM Lesson",
        channel: "BartonSnooker",
      },
      {
        id: "lthLtUJawq0",
        title: "Don't Make These Mistakes When Clearing the Colours",
        channel: "Stephen Hendry's Cue Tips",
      }
    ),
  },
  {
    id: "routine-3-reds-colours",
    category_id: "cat-break-building",
    name: "3 Reds + Colours Clearance",
    icon: "3️⃣",
    difficulty: "intermediate",
    summary: "Short-format break-building with emphasis on colour choice and cue-ball placement.",
    description: "A compact break-building routine that creates realistic decisions over only a few reds.",
    setup_instructions: "Place 3 open reds around the pink and black area and keep all colours on their spots.",
    steps: ["Pot a red and choose the best available colour for the next red.", "Preserve simple access to the remaining reds.", "After the reds are gone, clear the colours in sequence."],
    success_criteria: "Log your best single attempt out of 51, then note how many full 3-red clearances you complete in 10 attempts.",
    improves: ["Shot selection", "Mini-break conversion", "End-game focus"],
    scoring_type: "points",
    max_score: 51,
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "VBQPVRbPJnk",
        title: "3 Reds + Colours Clearance Practice Routine",
        channel: "OneFourStephen",
      },
      {
        id: "I5nkzi55xbs",
        title: "Snooker Practice | 3 Reds Break Building | Snooker Lesson",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-break-building-foundations",
    category_id: "cat-break-building",
    name: "Break Building Foundations",
    icon: "📊",
    difficulty: "intermediate",
    summary: "Build break-building habits through repeatable, low-risk scoring patterns.",
    description: "Focus on open reds, key-ball awareness, and controlled cue-ball movement in the scoring area.",
    setup_instructions: "Open 8-10 reds around the pink and black area.",
    steps: ["Choose a simple starter red.", "Play for the highest-percentage colour each time.", "Stop after each breakdown and review the shot or positional error that caused it."],
    success_criteria: "Log total points scored for the session. Also track the number of visits above 20 and how often the first red leads to a controlled scoring chance.",
    improves: ["Break conversion", "Risk control", "Frame scoring"],
    scoring_type: "points",
    estimated_duration_minutes: 25,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "48X9fjRbCso",
        title: "6 Steps To Make Your First 100+ Break",
        channel: "Stephen Hendry's Cue Tips",
      },
      {
        id: "D_x1wCMscYo",
        title: "Snooker Beginner Break Building - Snooker Lesson",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-pink-ball-routine",
    category_id: "cat-break-building",
    name: "Shots Around The Pink",
    icon: "🩷",
    difficulty: "advanced",
    summary: "Positional control routine built around pink-ball angles.",
    description: "Improve precision around the pink and nearby reds while keeping the cue-ball on the correct side of the shot.",
    setup_instructions: "Place two reds near the pink with different approach angles.",
    steps: ["Alternate between the two reds each visit.", "Land on the preferred angle for the pink each time.", "Complete 10 cycles without losing position on the pink."],
    success_criteria: "Log total points scored for the session while holding the correct angle on the pink; use cycle completion as your quality check.",
    improves: ["Pink control", "Angle choice", "Cluster navigation"],
    scoring_type: "points",
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "CU8Xv_Q2nao",
        title: "Snooker Practice - Two Reds & Pink - Snooker Lesson",
        channel: "BartonSnooker",
      },
      {
        id: "2Paa5oRQQ08",
        title: "Snooker - Pink Cross Practice Routine",
        channel: "Ian Burns Snooker Coaching",
      }
    ),
  },
  {
    id: "routine-baulk-safety",
    category_id: "cat-safety",
    name: "Snooker Safety Shots off Reds",
    icon: "🧱",
    difficulty: "advanced",
    summary: "Touch-based safety drill off reds to leave the cue-ball safe in baulk.",
    description: "Practise thin safety contacts that send the cue-ball back to baulk while nudging the red towards the black end.",
    setup_instructions: "Use one red at a time in 6 positions along a line parallel to the top cushion, starting level with the black spot. Play each attempt with the cue-ball in hand from the D.",
    steps: ["From each position, contact the red with controlled pace and return the cue-ball towards the baulk cushion area.", "Try to finish behind a baulk colour while moving the red back towards the black end.", "Score each shot out of 3: cue-ball cover, distance into baulk, and whether the red finishes safe."],
    success_criteria: "Target 12+ points out of 18 per round. Log each round separately and watch the average.",
    improves: ["Containment", "Safety pace", "Tactical pressure"],
    scoring_type: "count",
    max_score: 18,
    estimated_duration_minutes: 25,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "Q90ERw5UWfI",
        title: "Safety Play",
        channel: "Shaun Murphy Snooker",
      },
      {
        id: "190nfKvSY4M",
        title: "22. Safety - Practice Exercises",
        channel: "Barry Stark Snooker Coach",
      }
    ),
  },
  {
    id: "routine-escape-science",
    category_id: "cat-safety",
    name: "Escape Science Drill",
    icon: "🧭",
    difficulty: "advanced",
    summary: "Systematic escape training from common snookers.",
    description: "Build reliable escape percentages from the types of snookers players face most often in frames.",
    setup_instructions: "Create 10 snookers using the colours and baulk-line positions as the covering balls.",
    steps: ["Name the intended contact point before the shot.", "Play a legal escape while still considering where the cue-ball will finish.", "Record whether you made the hit and whether the resulting safety was acceptable."],
    success_criteria: "2 points for legal escape + safe leave, 1 for legal hit only (max 20).",
    improves: ["Escape decision-making", "Swerve/judgement", "Damage limitation"],
    scoring_type: "count",
    max_score: 20,
    estimated_duration_minutes: 25,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube({
      id: "bC1wyWXnp0Y",
      title: "SNOOKER ESCAPE SCIENCE",
      channel: "Cuestars",
    }),
  },
  {
    id: "routine-two-cushion-escape",
    category_id: "cat-safety",
    name: "Two Cushion Escape Drill",
    icon: "2️⃣",
    difficulty: "advanced",
    summary: "Improve reliability on two-cushion escape paths.",
    description: "Teaches contact references and pace for common two-cushion escapes.",
    setup_instructions: "Set 8 snookers where the direct path is blocked but a two-cushion escape is available.",
    steps: ["Pick the cushion contact point.", "Play with positive, controlled pace.", "Repeat each setup from both sides."],
    success_criteria: "Legal-hit percentage over 16 attempts (each snooker played from both sides).",
    improves: ["Cushion maps", "Escape confidence", "Tactical resilience"],
    scoring_type: "percentage",
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "V0XCCgOJPAY",
        title: "Snooker escapes - Mastering 1, 2, 3 cushions escapes (Know How)",
        channel: "Schulte Coach",
      },
      {
        id: "50PzObs5Aos",
        title: "Snooker-two cushions escape",
        channel: "Marek Potter",
      }
    ),
  },
  {
    id: "routine-three-cushion-escape",
    category_id: "cat-safety",
    name: "Three Cushion Escape Drill",
    icon: "3️⃣",
    difficulty: "advanced",
    summary: "Advanced escape-path work for deep snookers.",
    description: "Practise three-cushion escapes for positions where safer one- or two-cushion paths are not available.",
    setup_instructions: "Set 6 difficult snookers where one- and two-cushion escapes are either blocked or very low percentage.",
    steps: ["Visualise the full three-cushion path before you play.", "Control pace so you avoid leaving an easy chance.", "Grade each attempt for both legality and the quality of the safety left behind."],
    success_criteria: "Track legal-hit percentage and safe-leave percentage separately.",
    improves: ["Escape route selection", "Cushion speed control", "Composure"],
    scoring_type: "percentage",
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube({
      id: "A8ymzcMRXIA",
      title: "Snooker escape-Three cushions and more",
      channel: "Marek Potter",
    }),
  },
  {
    id: "routine-straight-cueing-line",
    category_id: "cat-straight-cueing",
    name: "Straight Potting Reds",
    icon: "📍",
    difficulty: "beginner",
    summary: "Straight-potting reds routine to expose cueing and aiming drift.",
    description: "A 15-red straight-potting format that quickly reveals repeated cut too thin and cut too thick tendencies.",
    setup_instructions: "Place one red on the centre line midway between the blue and brown spots, then 7 reds each side of it in an even row across the table, about 4 inches apart. Play from the baulk line and pot the reds as straight pots into the top corner pockets.",
    steps: ["Start with centre-ball delivery and treat each red as a straight pot.", "Optional scoring: 2 points for a clean pot, 1 for a pot that rattles in the jaws, 0 if the red contacts the cushion first.", "Log miss side and pocket entry to identify your repeated error pattern."],
    success_criteria: "Log your score out of 30: 2 points for a clean pot, 1 for a rattle that stays out.",
    improves: ["Cue straightness", "Head stillness", "Centre-ball confidence"],
    scoring_type: "points",
    max_score: 30,
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "UZeeYTCXlhI",
        title: "Snooker Mindset For STRAIGHT CUEING | Snooker Routine",
        channel: "BartonSnooker",
      },
      {
        id: "dQnL-Ot7jXA",
        title: "Snooker Straight Cueing How To Practice",
        channel: "Break from life",
      }
    ),
  },
  {
    id: "routine-long-blue-straight-cue",
    category_id: "cat-long-potting",
    name: "Long Blues",
    icon: "🔵",
    difficulty: "intermediate",
    summary: "Match-style long-blue confidence builder from progressive distances.",
    description: "Build a reliable long blue as a recovery pot when ideal position has been lost.",
    setup_instructions: "Place blue on spot. Set cue-ball on a straight line to a corner pocket from 2ft, then move to 3ft and 4ft as consistency improves.",
    steps: ["Pot 5-10 long blues into each corner from the current distance.", "Repeat at longer distances while keeping tempo and cueing rhythm constant.", "Record make percentage per pocket and per distance."],
    success_criteria: "Hit your target percentage at one distance before moving further back.",
    improves: ["Long cueing", "Shot conviction", "Aiming consistency"],
    scoring_type: "percentage",
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube({
      id: "Q-iskgM3P0E",
      title: "Straight Cueing Drill - Long Blue Pot",
      channel: "OneFourStephen",
    }),
  },
  {
    id: "routine-cueing-secret-session",
    category_id: "cat-straight-cueing",
    name: "Free Up the Cueing Arm",
    icon: "🎥",
    difficulty: "intermediate",
    summary: "Loose-arm warm-up session focused on flow and relaxed cue delivery.",
    description: "A lower-pressure reds-only session used to free the cueing arm and rebuild smooth rhythm.",
    setup_instructions: "Place 15 reds in a straight central line up the table and choose a starting red nearer the baulk end.",
    steps: ["Pot reds in order or in a chosen sequence while keeping the cue-ball off the cushions where possible.", "Stay loose through the grip and cueing arm, prioritising rhythm over power.", "Either reset after every miss for a stricter practice mode, or continue the visit for a confidence-building mode."],
    success_criteria: "Log total points scored out of 15 reds per set, then track cueing smoothness and visit quality across sets.",
    improves: ["Technique reset", "Strike quality", "Self-diagnosis"],
    scoring_type: "points",
    max_score: 15,
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube({
      id: "FEntZrOzjBM",
      title: "SNOOKER CUEING - The Secret To Good Snooker",
      channel: "BartonSnooker",
    }),
  },
  {
    id: "routine-cue-ball-control",
    category_id: "cat-cue-ball-control",
    name: "Cue Ball Control",
    icon: "📈",
    difficulty: "intermediate",
    summary: "Five-tip-position drill for understanding top, stun and screw response.",
    description: "Learn cue-ball behaviour by striking different heights on the vertical centre line of the cue-ball.",
    setup_instructions: "Place blue on blue spot. Place cue-ball about 10 inches (250mm) away on a straight line to the middle pocket. Use five tip heights: maximum top (about a tip above centre), half a tip above centre, dead centre, half a tip below centre, and maximum screw (about a tip below centre). Never strike beyond a tip from centre or you will miscue.",
    steps: ["Play 5 shots from each tip-height position with a smooth, standard cue action.", "Observe whether the cue-ball runs through, holds, or screws back, and by how much.", "Keep the arm and grip relaxed and deliver fully through the cue-ball."],
    success_criteria: "Log cue-ball finish outcomes for all 25 shots and note repeatability per tip height.",
    improves: ["Spin control", "Pace judgement", "Positional trust"],
    scoring_type: "count",
    max_score: 25,
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "Zz6Afney-fo",
        title: "Stephen Hendry's Number 1 Routine To IMPROVE Cue Ball Control",
        channel: "Stephen Hendry's Cue Tips",
      },
      {
        id: "JA-QGjD7WMA",
        title: "How To Play Top Spin, Stun, & Screw",
        channel: "Stephen Hendry's Cue Tips",
      }
    ),
  },
  {
    id: "routine-stun-run-through",
    category_id: "cat-cue-ball-control",
    name: "Stun Run Through",
    icon: "➡️",
    difficulty: "intermediate",
    summary: "Control stun-run-through distance through progressive straight and slight-angle shots.",
    description: "Train consistent stun timing so the cue-ball runs through cleanly without drifting off line.",
    setup_instructions: "Set 5 repeatable red positions from short to medium distance with clear target zones.",
    steps: ["Play each shot with stun-run pace only.", "Hold cueing tempo constant through all 5 positions.", "Track if cue ball lands long, short, or on target."],
    success_criteria: "Count target-zone landings from 20 attempts.",
    improves: ["Stun distance control", "Timing", "Positional consistency"],
    scoring_type: "count",
    max_score: 20,
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "nIv4dLqXM3M",
        title: "Snooker STUN RUN THROUGH | Snooker Tips",
        channel: "BartonSnooker",
      },
      {
        id: "eP8razaeiZA",
        title: "Snooker Stun Run Through - How To Play - Tutorial",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-top-spin-control",
    category_id: "cat-cue-ball-control",
    name: "Top Spin Control",
    icon: "⬆️",
    difficulty: "intermediate",
    summary: "Develop clean follow contact and reliable run-through distances.",
    description: "Use this routine to improve forward cue-ball travel while keeping the potting line stable.",
    setup_instructions: "Set one object ball and mark 4 cue-ball landing zones at increasing run-through distances.",
    steps: ["Play plain-ball follow first, then add a little more top as needed.", "Match cue speed to the landing zone you called.", "Repeat each zone 4 times before moving on."],
    success_criteria: "Count successful landings from 16 attempts.",
    improves: ["Topspin contact", "Distance control", "Line retention"],
    scoring_type: "count",
    max_score: 16,
    estimated_duration_minutes: 16,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube({
      id: "l6cTzXMuEzM",
      title: "How To Generate MAXIMUM Top Spin!",
      channel: "BartonSnooker",
    }),
  },
  {
    id: "routine-side-spin-control",
    category_id: "cat-cue-ball-control",
    name: "Side Spin Control",
    icon: "↪️",
    difficulty: "advanced",
    summary: "Build confidence applying side without losing cue-ball control.",
    description: "Practise left and right side, aiming adjustment, and pace control in snooker-style positional patterns.",
    setup_instructions: "Set 6 shots where side changes the cue-ball path around another ball or into a marked target zone.",
    steps: ["Call the side and expected cue-ball path before each shot.", "Use controlled cue speed and a positive strike.", "Log both cue-ball path accuracy and pot success."],
    success_criteria: "Track cue-ball path success percentage over 18 attempts.",
    improves: ["Angle control on the blue", "Aiming adjustment", "Route shaping"],
    scoring_type: "percentage",
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "Ab-xw7QxLJo",
        title: "How To Aim With Side Correctly",
        channel: "Stephen Hendry's Cue Tips",
      },
      {
        id: "mT1QQxcPjcM",
        title: "Snooker | Ultimate Guide to Side Spin | Tutorial",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-stun-line",
    category_id: "cat-cue-ball-control",
    name: "Mastering Stun Shots",
    icon: "➖",
    difficulty: "intermediate",
    summary: "Train true stun response from straight pots through to half-ball angles.",
    description: "Use this to stop the cue-ball overrunning and to improve positional precision from stun.",
    setup_instructions: "Set 6 shots: 2 straight, 2 three-quarter-ball and 2 half-ball.",
    steps: ["Play all shots with stun only.", "On the straight shots the cue-ball should stop dead; on the angled ones it should run along the tangent line.", "Check the cue-ball finish against your chosen marker and repeat until the finish line becomes repeatable."],
    success_criteria: "Land within one-ball tolerance on 12 of 18 attempts.",
    improves: ["Stun timing", "Cue-ball hold", "Route precision"],
    scoring_type: "count",
    max_score: 18,
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "DY0CNNq64Vw",
        title: "Understand and MASTER The STUN SHOT",
        channel: "BartonSnooker",
      },
      {
        id: "Hx0R01_SaO8",
        title: "34. Stun for Control - Improve stun shot play",
        channel: "Barry Stark Snooker Coach",
      }
    ),
  },
  {
    id: "routine-screw-back",
    category_id: "cat-cue-ball-control",
    name: "Screw Back Drill",
    icon: "↩️",
    difficulty: "intermediate",
    summary: "Develop reliable short and medium screw-back distances.",
    description: "A progression drill for low contact on the cue-ball and controlled acceleration through the shot.",
    setup_instructions: "Set one object ball near middle pocket and mark 3 screw-back distances.",
    steps: ["Play 5 screw-back shots into the short zone.", "Play 5 into the medium zone.", "Play 5 into the deep zone."],
    success_criteria: "Count landings inside the target zones from 15 attempts.",
    improves: ["Low-ball contact", "Power control", "Recovery play"],
    scoring_type: "count",
    max_score: 15,
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "IS3SJ7jgJSg",
        title: "3 Reasons Why You Can't Screw Back!",
        channel: "BartonSnooker",
      },
      {
        id: "18dR11PwRJY",
        title: "Snooker Spin Screw Back Maximum Back Spin",
        channel: "Break from life",
      }
    ),
  },
  {
    id: "routine-deep-screw",
    category_id: "cat-cue-ball-control",
    name: "Deep Screw Drill",
    icon: "💥",
    difficulty: "advanced",
    summary: "Generate deep screw without losing potting line.",
    description: "Advanced drill for powerful screw-back shots with stable cue delivery.",
    setup_instructions: "Use straight and slight-angle shots at increasing cue-ball distance.",
    steps: ["Play 10 deep screw-back shots.", "Keep the same cue-speed profile throughout.", "Log under-hit and over-hit outcomes."],
    success_criteria: "At least 6 of 10 attempts return to target distance band.",
    improves: ["Power generation", "Low-ball precision", "Delivery control"],
    scoring_type: "count",
    max_score: 10,
    estimated_duration_minutes: 15,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube({
      id: "FUMM2Ed4VmU",
      title: "How To Play The Long Deep Screw Back | Snooker",
      channel: "BartonSnooker",
    }),
  },
  {
    id: "routine-long-potting-classic",
    category_id: "cat-long-potting",
    name: "Potting Long Reds",
    icon: "🏆",
    difficulty: "intermediate",
    summary: "Long-red opener drill with stun hold for the pink.",
    description: "Practise potting a long red and holding the cue-ball near the red's starting position to leave the pink on.",
    setup_instructions: "Place the pink on its spot. Place the pink on its spot and a red about a foot from it, towards a top corner pocket. Put the cue-ball on the extension of that red-to-pocket line, back towards baulk. Place the cue-ball on the same line, roughly halfway between the blue and the baulk colours.",
    steps: ["Strike slightly below centre to pot the red with stun into the end pocket.", "Aim to stop the cue-ball on or near the red's original position for the pink.", "Repeat from both sides with 5-10 attempts per side, moving the cue-ball further back as control improves."],
    success_criteria: "Track long-red pot percentage and successful stun-hold percentage separately.",
    improves: ["Distance potting", "Shot conviction", "Opening-shot confidence"],
    scoring_type: "percentage",
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "jzi2WbXv-E0",
        title: "The Truth About Long Potting - Snooker",
        channel: "Ian Burns Snooker Coaching",
      },
      {
        id: "h6H4sSf4vZ0",
        title: "43. Long Potting - Practice for success",
        channel: "Barry Stark Snooker Coach",
      }
    ),
  },
  {
    id: "routine-black-off-spot",
    category_id: "cat-break-building",
    name: "Potting The Black Ball",
    icon: "⚫",
    difficulty: "intermediate",
    summary: "Black-spot repetition drill for angle control and position discipline.",
    description: "Repeated black pots sharpen potting line, touch, and composure in the main scoring area.",
    setup_instructions: "Place the black on its spot. Start the cue-ball level with the black, about halfway to the side cushion, for a three-quarter-ball angle. Move it further towards the cushion for half-ball and then quarter-ball angles.",
    steps: ["Begin with straightforward blacks into the corner pockets and build towards tougher angles.", "Keep the pattern simple and prioritise cue-ball control for the next black.", "Track makes and the type of miss as the angle widens or the cue-ball drifts towards the cushions."],
    success_criteria: "Best uninterrupted black run and total makes per 25-ball set.",
    improves: ["Black-ball potting", "Pace control", "Cueing precision"],
    scoring_type: "count",
    max_score: 25,
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "lLYEZpMoZz8",
        title: "The best angle on the black!",
        channel: "BartonSnooker",
      },
      {
        id: "86wIb7G6Qqg",
        title: "Why I Missed An Easy Pot.. Explained to try to stop it happening. (Snooker T Practice Routine)",
        channel: "Break Into Snooker",
      }
    ),
  },
  {
    id: "routine-blue-ball-control",
    category_id: "cat-break-building",
    name: "Reds and the Blue",
    icon: "🔷",
    difficulty: "intermediate",
    summary: "Blue-ball break-building drill for when the pink and black are unavailable.",
    description: "Practise controlling the angle on the blue so you can keep bringing reds into play around the middle of the table.",
    setup_instructions: "Place all colours on their spots. Set 3 reds between the blue and brown spots and 3 between the blue and pink spots, spread along the centre line, 6 reds in total to start.",
    steps: ["Start with a red-to-blue pattern and aim to stay on the correct side of the blue.", "Use fine pace so the cue-ball travels the minimum distance between shots.", "When you clear 6 reds consistently, add extra reds to make the pattern tougher."],
    success_criteria: "Record total points scored per set; also track full-clear count and red-to-blue conversion as supporting quality metrics.",
    improves: ["Blue-ball confidence", "Angle control on the blue", "Route understanding"],
    scoring_type: "points",
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "iFNETOzgSts",
        title: "Snooker Blue Ball Common Shots PART 2 - Snooker Lesson",
        channel: "BartonSnooker",
      },
      {
        id: "HYFmkCzJZ7A",
        title: "Snooker Side Spin On The Blue - Snooker Training",
        channel: "BartonSnooker",
      }
    ),
  },
  ...EXTRA_ROUTINES,
];

/**
 * The drills written before the library had diagrams get theirs attached here, so those entries
 * stay readable and a routine without a picture simply passes through unchanged.
 */
export const DEFAULT_ROUTINES: Routine[] = ROUTINE_LIST.map((routine) =>
  routine.diagram || !FIRST_WAVE_DIAGRAMS[routine.id]
    ? routine
    : { ...routine, diagram: FIRST_WAVE_DIAGRAMS[routine.id] }
);
