import { Routine, RoutineCategory } from "../types";
import { getYoutubeWatchUrl } from "../utils/youtube";

type VideoMeta = {
  id: string;
  title: string;
  channel: string;
};

const now = new Date().toISOString();

const withYouTube = (primary: VideoMeta, alternate?: VideoMeta) => ({
  youtube_video_id: primary.id,
  youtube_url: getYoutubeWatchUrl(primary.id),
  youtube_title: primary.title,
  youtube_channel: primary.channel,
  youtube_alt_video_id: alternate?.id,
  youtube_alt_url: alternate ? getYoutubeWatchUrl(alternate.id) : undefined,
  youtube_alt_title: alternate?.title,
  youtube_alt_channel: alternate?.channel,
});

export const DEFAULT_CATEGORIES: RoutineCategory[] = [
  {
    id: "cat-basics",
    name: "The Foundations",
    description: "Essential building blocks: stance, bridge, sighting and potting.",
    icon: "🎯",
    color: "#0F766E",
    order_index: 1,
    created_at: now,
  },
  {
    id: "cat-break-building",
    name: "Break Building",
    description: "Pattern drills for converting chances into bigger visits.",
    icon: "🔥",
    color: "#B45309",
    order_index: 2,
    created_at: now,
  },
  {
    id: "cat-safety",
    name: "Safety",
    description: "Containment and escape routines for tactical control.",
    icon: "🛡️",
    color: "#1D4ED8",
    order_index: 3,
    created_at: now,
  },
  {
    id: "cat-straight-cueing",
    name: "Straight Cueing",
    description: "Cue alignment and strike quality training.",
    icon: "🎱",
    color: "#334155",
    order_index: 4,
    created_at: now,
  },
  {
    id: "cat-cue-ball-control",
    name: "Cue Ball Control",
    description: "Stun, screw and pace drills for precise position play.",
    icon: "📈",
    color: "#7C3AED",
    order_index: 5,
    created_at: now,
  },
  {
    id: "cat-long-potting",
    name: "Long Potting",
    description: "Distance potting confidence from match-like positions.",
    icon: "🏆",
    color: "#BE123C",
    order_index: 6,
    created_at: now,
  },
];

export const DEFAULT_ROUTINES: Routine[] = [
  {
    id: "routine-bridge-grip-stance",
    category_id: "cat-basics",
    name: "Stance Fundamentals",
    icon: "🧍",
    difficulty: "beginner",
    summary: "Build a repeatable stance that supports straight cueing.",
    description: "Use simple shots and focus on balance, head stability and body alignment.",
    setup_instructions: "Set 6 easy reds in open positions to both middle and corner pockets.",
    steps: ["Set feet and shoulder line before dropping down.", "Keep head still through contact.", "Hold finish for two seconds after each shot."],
    success_criteria: "Complete 24 reps and record how many meet all stance checkpoints.",
    improves: ["Balance", "Head stillness", "Setup repeatability"],
    scoring_type: "count",
    estimated_duration_minutes: 15,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "olOV1TVMqtI",
        title: "The Stance",
        channel: "Shaun Murphy Snooker",
      },
      {
        id: "pOWMCJLlQxc",
        title: "The SNOOKER SETUP | Important Details",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-pre-shot-routine",
    category_id: "cat-basics",
    name: "Bridge Fundamentals",
    icon: "✋",
    difficulty: "beginner",
    summary: "Develop stable bridge shapes for straighter cue delivery.",
    description: "Train open and closed bridge quality so the cue runs freely on the line.",
    setup_instructions: "Use one medium-straight red and repeat from two cue-ball distances.",
    steps: ["Build bridge first, then place cue on line.", "Check bridge length and hand pressure.", "Alternate open and closed bridge every 5 shots."],
    success_criteria: "Complete 20 reps and record how many keep the cue centered in the bridge channel.",
    improves: ["Bridge stability", "Cue support", "Strike consistency"],
    scoring_type: "count",
    estimated_duration_minutes: 15,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "jgysxTFjULE",
        title: "The Bridge",
        channel: "Shaun Murphy Snooker",
      },
      {
        id: "rxSg2ciaV8A",
        title: "The Perfect Bridge Hand Position",
        channel: "Stephen Hendry's Cue Tips",
      }
    ),
  },
  {
    id: "routine-rest-shot-fundamentals",
    category_id: "cat-basics",
    name: "Sighting Fundamentals",
    icon: "👁️",
    difficulty: "beginner",
    summary: "Learn to identify and hold the true shot line.",
    description: "Sighting routine focused on alignment before you get down on the shot.",
    setup_instructions: "Set 8 near-straight pots at different table points, including two long pots.",
    steps: ["Stand behind cue ball to identify pot line.", "Step in with cue and dominant-eye line aligned.", "Deliver only when cue tip settles exactly on line."],
    success_criteria: "Track cleanly sighted pots out of 24 attempts.",
    improves: ["Aiming clarity", "Line commitment", "Pre-shot discipline"],
    scoring_type: "percentage",
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "CJHVs0SN4jI",
        title: "A Dummies Guide to Sighting",
        channel: "Shaun Murphy Snooker",
      },
      {
        id: "nSVc5gvvlmc",
        title: "08. Aiming in Snooker - Where should you look?",
        channel: "Barry Stark Snooker Coach",
      }
    ),
  },
  {
    id: "routine-potting-fundamentals",
    category_id: "cat-basics",
    name: "Potting Fundamentals",
    icon: "🎯",
    difficulty: "beginner",
    summary: "Core potting technique for reliable strike and pocket entry.",
    description: "Use simple to moderate pots to build potting confidence and clean cue action.",
    setup_instructions: "Set 10 pots: 4 short, 4 medium and 2 long from baulk to top corners.",
    steps: ["Keep full pre-shot rhythm.", "Commit to center-ball hit unless spin is called.", "Note every miss type: thick, thin or pace."],
    success_criteria: "Total makes from 30 attempts; track miss pattern for next session.",
    improves: ["Potting reliability", "Pocket acceptance", "Match confidence"],
    scoring_type: "count",
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "Ba6TqwXogSA",
        title: "Potting terminology explained...",
        channel: "Shaun Murphy Snooker",
      },
      {
        id: "ilS_YOUpf9s",
        title: "Master Your Potting Angles (The Easy Way!)",
        channel: "Stephen Hendry's Cue Tips",
      }
    ),
  },
  {
    id: "routine-line-up",
    category_id: "cat-break-building",
    name: "The Line-Up",
    icon: "🔥",
    difficulty: "intermediate",
    summary: "Classic 15-red line-up for break-building control.",
    description: "Develop angle management, cue-ball control, and recovery choices around the pink/black area.",
    setup_instructions: "Set 15 reds in a line-up pattern under the pink area with colors on spots.",
    steps: ["Prioritize simple reds first.", "Play for black whenever angle allows.", "Recover to blue when out of line."],
    success_criteria: "Track best break and average of 5 visits.",
    improves: ["Break continuity", "Angle management", "Recovery choices"],
    scoring_type: "points",
    max_score: 147,
    estimated_duration_minutes: 30,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "3CKs5pmfss4",
        title: "The Line Up",
        channel: "Shaun Murphy Snooker",
      },
      {
        id: "vv2Wjdf3wl8",
        title: "Snooker Line-Up Tutorial - Snooker Lesson",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-t-routine",
    category_id: "cat-break-building",
    name: "The T Routine",
    icon: "📐",
    difficulty: "advanced",
    summary: "Pattern-discipline drill using reds in a T shape.",
    description: "Train route planning and efficient cue-ball travel through the center of the table.",
    setup_instructions: "Arrange reds in a T shape around the blue spot lane.",
    steps: ["Plan 3 shots ahead.", "Stay on the correct side of each red.", "Reset after each miss and re-plan."],
    success_criteria: "Count completed T clearances and total successful visits in 30 minutes.",
    improves: ["Pattern planning", "Cue-ball routes", "Discipline"],
    scoring_type: "count",
    estimated_duration_minutes: 30,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "oU3-Cl-N59I",
        title: "Snooker T Practice Routine",
        channel: "Barry Stark Snooker Coach",
      },
      {
        id: "CjBAH5FV4EM",
        title: "Snooker T Exercise - Discipline & Consistency",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-around-colours",
    category_id: "cat-break-building",
    name: "Around The Colours",
    icon: "🌈",
    difficulty: "intermediate",
    summary: "Colour-clearance routine for cue-ball touch and planning.",
    description: "Run colors in order while keeping cue-ball paths compact and controlled.",
    setup_instructions: "Use all colors on spots and start cue ball in baulk.",
    steps: ["Call intended cue-ball lane before each color.", "Avoid over-hitting recovery shots.", "Restart sequence on any miss."],
    success_criteria: "Number of full color clearances completed in 20 minutes.",
    improves: ["Touch", "Planning", "Finishing frames"],
    scoring_type: "count",
    max_score: 10,
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "NaWnabDwkEU",
        title: "SNOOKER Colours Clearance | HEADCAM Lesson",
        channel: "BartonSnooker",
      },
      {
        id: "lthLtUJawq0",
        title: "Don't Make These Mistakes When Clearing the Colours",
        channel: "Stephen Hendry's Cue Tips",
      }
    ),
  },
  {
    id: "routine-3-reds-colours",
    category_id: "cat-break-building",
    name: "3 Reds + Colours Clearance",
    icon: "3️⃣",
    difficulty: "intermediate",
    summary: "Short-format break-building with pressure on color choice.",
    description: "A compact routine for players who want realistic break decisions in short blocks.",
    setup_instructions: "Place 3 open reds near black/pink area and keep all colors on spots.",
    steps: ["Pot a red then best available color.", "Preserve easy red access.", "Finish with all colors in sequence."],
    success_criteria: "Count full 3-red clearances from 10 attempts.",
    improves: ["Shot selection", "Mini-break conversion", "End-game focus"],
    scoring_type: "count",
    max_score: 10,
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "VBQPVRbPJnk",
        title: "3 Reds + Colours Clearance Practice Routine",
        channel: "OneFourStephen",
      },
      {
        id: "I5nkzi55xbs",
        title: "Snooker Practice | 3 Reds Break Building | Snooker Lesson",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-break-building-foundations",
    category_id: "cat-break-building",
    name: "Break Building Foundations",
    icon: "📊",
    difficulty: "intermediate",
    summary: "Build break-building habits through repeatable, low-risk patterns.",
    description: "Focus on simple reds, key-ball awareness, and controlled cue-ball travel.",
    setup_instructions: "Open 8-10 reds around pink/black zones.",
    steps: ["Choose easy starter red.", "Play for high-percentage color only.", "Stop and review every breakdown."],
    success_criteria: "Track number of visits above 20 and conversion rate from first red to color control.",
    improves: ["Break conversion", "Risk control", "Frame scoring"],
    scoring_type: "count",
    estimated_duration_minutes: 25,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "48X9fjRbCso",
        title: "6 Steps To Make Your First 100+ Break",
        channel: "Stephen Hendry's Cue Tips",
      },
      {
        id: "D_x1wCMscYo",
        title: "Snooker Beginner Break Building - Snooker Lesson",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-pink-ball-routine",
    category_id: "cat-break-building",
    name: "Shots Around The Pink",
    icon: "🩷",
    difficulty: "advanced",
    summary: "Positional control routine around pink-zone angles.",
    description: "Improve precision around pink and nearby reds while keeping cue-ball paths simple.",
    setup_instructions: "Place two reds near pink with different approach angles.",
    steps: ["Alternate reds each visit.", "Land on ideal pink angle.", "Complete 10 cycles with no positional miss."],
    success_criteria: "Percentage of cycles completed without losing pink position.",
    improves: ["Pink control", "Angle choice", "Cluster navigation"],
    scoring_type: "percentage",
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "CU8Xv_Q2nao",
        title: "Snooker Practice - Two Reds & Pink - Snooker Lesson",
        channel: "BartonSnooker",
      },
      {
        id: "2Paa5oRQQ08",
        title: "Snooker - Pink Cross Practice Routine",
        channel: "Ian Burns Snooker Coaching",
      }
    ),
  },
  {
    id: "routine-baulk-safety",
    category_id: "cat-safety",
    name: "Safety Basics",
    icon: "🧱",
    difficulty: "advanced",
    summary: "Build repeatable safety pace and cue-ball containment.",
    description: "A practical safety routine focused on distance control and reducing return-pot chances.",
    setup_instructions: "Set 6 common safety starts from open table and edge-of-pack positions.",
    steps: ["Play return-to-baulk safety.", "Judge contact thickness and pace.", "Repeat each position 3 times."],
    success_criteria: "Score 2 points for baulk return, 1 for thin safety, 0 for sell-out (max 36).",
    improves: ["Containment", "Safety pace", "Tactical pressure"],
    scoring_type: "count",
    max_score: 36,
    estimated_duration_minutes: 25,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "Q90ERw5UWfI",
        title: "Safety Play",
        channel: "Shaun Murphy Snooker",
      },
      {
        id: "190nfKvSY4M",
        title: "22. Safety - Practice Exercises",
        channel: "Barry Stark Snooker Coach",
      }
    ),
  },
  {
    id: "routine-escape-science",
    category_id: "cat-safety",
    name: "Escape Science Drill",
    icon: "🧭",
    difficulty: "advanced",
    summary: "Systematic one- and two-cushion escape training.",
    description: "Build dependable escape percentages from common snooker positions.",
    setup_instructions: "Create 10 snookers behind colors and baulk line positions.",
    steps: ["Call contact point before shooting.", "Play legal escape with cue-ball control.", "Record direct-hit and safety outcome."],
    success_criteria: "2 points for legal escape + safe leave, 1 for legal hit only (max 20).",
    improves: ["Escape decision-making", "Swerve/judgment", "Damage limitation"],
    scoring_type: "count",
    max_score: 20,
    estimated_duration_minutes: 25,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube({
      id: "bC1wyWXnp0Y",
      title: "SNOOKER ESCAPE SCIENCE",
      channel: "Cuestars",
    }),
  },
  {
    id: "routine-two-cushion-escape",
    category_id: "cat-safety",
    name: "Two Cushion Escape Drill",
    icon: "2️⃣",
    difficulty: "advanced",
    summary: "Improve reliability on two-cushion escape routes.",
    description: "Teaches reference points and pace for common two-cushion escapes.",
    setup_instructions: "Set 8 snookers where direct path is blocked but two-cushion path exists.",
    steps: ["Pick cushion contact target.", "Play with committed pace.", "Repeat each setup from both sides."],
    success_criteria: "Legal-hit percentage over 24 attempts.",
    improves: ["Cushion maps", "Escape confidence", "Tactical resilience"],
    scoring_type: "percentage",
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "V0XCCgOJPAY",
        title: "Snooker escapes - Mastering 1, 2, 3 cushions escapes (Know How)",
        channel: "Schulte Coach",
      },
      {
        id: "50PzObs5Aos",
        title: "Snooker-two cushions escape",
        channel: "Marek Potter",
      }
    ),
  },
  {
    id: "routine-three-cushion-escape",
    category_id: "cat-safety",
    name: "Three Cushion Escape Drill",
    icon: "3️⃣",
    difficulty: "advanced",
    summary: "Advanced route-finding for deep snookers.",
    description: "Practice three-cushion escapes when low-risk options are limited.",
    setup_instructions: "Set 6 hard snookers where one- and two-cushion routes are blocked.",
    steps: ["Visualize full route first.", "Control pace to avoid leave-ons.", "Grade each attempt for legality and safety."],
    success_criteria: "Track legal-hit percentage and safe-leave percentage separately.",
    improves: ["Route imagination", "Cushion speed control", "Composure"],
    scoring_type: "percentage",
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube({
      id: "A8ymzcMRXIA",
      title: "Snooker escape-Three cushions and more",
      channel: "Marek Potter",
    }),
  },
  {
    id: "routine-straight-cueing-line",
    category_id: "cat-straight-cueing",
    name: "Straight Cueing Line Drill",
    icon: "📍",
    difficulty: "beginner",
    summary: "Core straight-line potting for delivery consistency.",
    description: "Simple straight shots repeated with strict technique standards.",
    setup_instructions: "Set red on blue spot line to middle pocket. Start cue ball one diamond away.",
    steps: ["Pot 10 in a row before moving back.", "Keep same pre-shot rhythm.", "Reset distance on any miss."],
    success_criteria: "Record longest uninterrupted run.",
    improves: ["Cue straightness", "Head stillness", "Center-ball confidence"],
    scoring_type: "count",
    max_score: 30,
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "UZeeYTCXlhI",
        title: "Snooker Mindset For STRAIGHT CUEING | Snooker Routine",
        channel: "BartonSnooker",
      },
      {
        id: "dQnL-Ot7jXA",
        title: "Snooker Straight Cueing How To Practice",
        channel: "Break from life",
      }
    ),
  },
  {
    id: "routine-long-blue-straight-cue",
    category_id: "cat-straight-cueing",
    name: "Long Blue Straight Cueing",
    icon: "🔵",
    difficulty: "intermediate",
    summary: "Straight cueing under long-distance pressure.",
    description: "Develop committed cue delivery on a repeated long blue.",
    setup_instructions: "Place blue on spot and cue ball in baulk for long blue to middle/corner pattern.",
    steps: ["Play 15 long blues.", "Keep identical tempo each shot.", "Log misses by side and overcut/undercut."],
    success_criteria: "Pot percentage from 15 attempts.",
    improves: ["Long cueing", "Commitment", "Aiming consistency"],
    scoring_type: "percentage",
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube({
      id: "Q-iskgM3P0E",
      title: "Straight Cueing Drill - Long Blue Pot",
      channel: "OneFourStephen",
    }),
  },
  {
    id: "routine-cueing-secret-session",
    category_id: "cat-straight-cueing",
    name: "Cueing Fundamentals Session",
    icon: "🎥",
    difficulty: "intermediate",
    summary: "Session template focused on clean strike mechanics.",
    description: "Use this when cueing quality drifts and you need a technique reset.",
    setup_instructions: "Alternate short and medium straight pots with center-ball contact only.",
    steps: ["Play in 5-shot blocks.", "Pause and self-review after each block.", "Rebuild setup if line drifts."],
    success_criteria: "Complete 6 blocks with at least 4 clean contacts per block.",
    improves: ["Technique reset", "Strike quality", "Self-diagnosis"],
    scoring_type: "count",
    max_score: 30,
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube({
      id: "FEntZrOzjBM",
      title: "SNOOKER CUEING - The Secret To Good Snooker",
      channel: "BartonSnooker",
    }),
  },
  {
    id: "routine-cue-ball-control",
    category_id: "cat-cue-ball-control",
    name: "Cue Ball Control Routine",
    icon: "📈",
    difficulty: "intermediate",
    summary: "Build consistent landing zones with stun, screw and follow.",
    description: "A complete control routine covering the three core cue-ball actions.",
    setup_instructions: "Use one object ball and mark 3 landing zones with coins/chalk.",
    steps: ["Play 5 stun shots to Zone A.", "Play 5 screw shots to Zone B.", "Play 5 follow shots to Zone C."],
    success_criteria: "Count successful landings from 15 attempts.",
    improves: ["Spin control", "Pace judgement", "Positional trust"],
    scoring_type: "count",
    max_score: 15,
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "Zz6Afney-fo",
        title: "Stephen Hendry's Number 1 Routine To IMPROVE Cue Ball Control",
        channel: "Stephen Hendry's Cue Tips",
      },
      {
        id: "JA-QGjD7WMA",
        title: "How To Play Top Spin, Stun, & Screw",
        channel: "Stephen Hendry's Cue Tips",
      }
    ),
  },
  {
    id: "routine-stun-run-through",
    category_id: "cat-cue-ball-control",
    name: "Stun Run Through",
    icon: "➡️",
    difficulty: "intermediate",
    summary: "Control stun distance through progressive straight and slight-angle shots.",
    description: "Train consistent stun timing so the cue ball runs through the line without drifting off route.",
    setup_instructions: "Set 5 repeatable red positions from short to medium distance with clear target zones.",
    steps: ["Play each shot with stun-run pace only.", "Hold cueing tempo constant through all 5 positions.", "Track if cue ball lands long, short, or on target."],
    success_criteria: "Count target-zone landings from 20 attempts.",
    improves: ["Stun distance control", "Timing", "Positional consistency"],
    scoring_type: "count",
    max_score: 20,
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "nIv4dLqXM3M",
        title: "Snooker STUN RUN THROUGH | Snooker Tips",
        channel: "BartonSnooker",
      },
      {
        id: "eP8razaeiZA",
        title: "Snooker Stun Run Through - How To Play - Tutorial",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-top-spin-control",
    category_id: "cat-cue-ball-control",
    name: "Top Spin Control",
    icon: "⬆️",
    difficulty: "intermediate",
    summary: "Develop clean topspin contact and reliable follow-through distances.",
    description: "Use this routine to improve forward cue-ball travel while keeping potting line stable.",
    setup_instructions: "Set one object ball and mark 4 follow-through landing bands at increasing distance.",
    steps: ["Play plain-ball follow first, then add controlled topspin.", "Match cue speed to the called landing band.", "Repeat each band 4 times before moving on."],
    success_criteria: "Count successful landings from 16 attempts.",
    improves: ["Topspin contact", "Distance control", "Line retention"],
    scoring_type: "count",
    max_score: 16,
    estimated_duration_minutes: 16,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube({
      id: "l6cTzXMuEzM",
      title: "How To Generate MAXIMUM Top Spin!",
      channel: "BartonSnooker",
    }),
  },
  {
    id: "routine-side-spin-control",
    category_id: "cat-cue-ball-control",
    name: "Side Spin Control",
    icon: "↪️",
    difficulty: "advanced",
    summary: "Build confidence applying side spin without losing cue-ball route control.",
    description: "Practice left/right side selection, aiming compensation, and pace control in match-style patterns.",
    setup_instructions: "Set 6 shots where side spin changes cue-ball path around a blocker or into a target lane.",
    steps: ["Call side and expected cue-ball route before each shot.", "Use controlled cue speed and committed strike.", "Log route accuracy and pot outcome together."],
    success_criteria: "Track route-completion percentage over 18 attempts.",
    improves: ["Side-spin judgment", "Aiming adjustment", "Route shaping"],
    scoring_type: "percentage",
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "Ab-xw7QxLJo",
        title: "How To Aim With Side Correctly",
        channel: "Stephen Hendry's Cue Tips",
      },
      {
        id: "mT1QQxcPjcM",
        title: "Snooker | Ultimate Guide to Side Spin | Tutorial",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-stun-line",
    category_id: "cat-cue-ball-control",
    name: "Mastering Stun Shots",
    icon: "➖",
    difficulty: "intermediate",
    summary: "Train true stun response on straight and slight-angle shots.",
    description: "Use this to stop over-running and improve route precision.",
    setup_instructions: "Set 6 shots with half-ball and three-quarter-ball contacts.",
    steps: ["Play all shots with stun only.", "Check stop line against marker.", "Repeat until line is repeatable."],
    success_criteria: "Land within one-ball tolerance on 12 of 18 attempts.",
    improves: ["Stun timing", "Cue-ball hold", "Route precision"],
    scoring_type: "count",
    max_score: 18,
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "DY0CNNq64Vw",
        title: "Understand and MASTER The STUN SHOT",
        channel: "BartonSnooker",
      },
      {
        id: "Hx0R01_SaO8",
        title: "34. Stun for Control - Improve stun shot play",
        channel: "Barry Stark Snooker Coach",
      }
    ),
  },
  {
    id: "routine-screw-back",
    category_id: "cat-cue-ball-control",
    name: "Screw Back Drill",
    icon: "↩️",
    difficulty: "intermediate",
    summary: "Develop reliable short and medium screw-back distances.",
    description: "A progression drill for low-ball contact and controlled acceleration.",
    setup_instructions: "Set one object ball near middle pocket and mark 3 screw-back distances.",
    steps: ["Play 5 screws to short zone.", "Play 5 to medium zone.", "Play 5 to deep zone."],
    success_criteria: "Count landings inside target windows from 15 attempts.",
    improves: ["Low-ball contact", "Power control", "Recovery play"],
    scoring_type: "count",
    max_score: 15,
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "IS3SJ7jgJSg",
        title: "3 Reasons Why You Can't Screw Back!",
        channel: "BartonSnooker",
      },
      {
        id: "18dR11PwRJY",
        title: "Snooker Spin Screw Back Maximum Back Spin",
        channel: "Break from life",
      }
    ),
  },
  {
    id: "routine-deep-screw",
    category_id: "cat-cue-ball-control",
    name: "Deep Screw Drill",
    icon: "💥",
    difficulty: "advanced",
    summary: "Generate deep screw without losing potting line.",
    description: "Advanced drill for strong draw shots with stable cue delivery.",
    setup_instructions: "Use straight and slight-angle shots at increasing cue-ball distance.",
    steps: ["Play 10 deep screw shots.", "Keep same cue speed profile.", "Log under-hit and over-hit outcomes."],
    success_criteria: "At least 6 of 10 attempts return to target distance band.",
    improves: ["Power generation", "Low-ball precision", "Delivery control"],
    scoring_type: "count",
    max_score: 10,
    estimated_duration_minutes: 15,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube({
      id: "FUMM2Ed4VmU",
      title: "How To Play The Long Deep Screw Back | Snooker",
      channel: "BartonSnooker",
    }),
  },
  {
    id: "routine-long-potting-classic",
    category_id: "cat-long-potting",
    name: "Long Potting Classic",
    icon: "🏆",
    difficulty: "intermediate",
    summary: "Alternating long reds from baulk to both corners.",
    description: "Build distance confidence using a repeatable match-start pattern.",
    setup_instructions: "Place two reds near top cushion left/right of pink spot line.",
    steps: ["Alternate left and right long red.", "Use same pre-shot routine every shot.", "Play blocks of 20 attempts."],
    success_criteria: "Pot percentage over 20 attempts.",
    improves: ["Distance potting", "Commitment", "Opening-shot confidence"],
    scoring_type: "percentage",
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "jzi2WbXv-E0",
        title: "The Truth About Long Potting - Snooker",
        channel: "Ian Burns Snooker Coaching",
      },
      {
        id: "h6H4sSf4vZ0",
        title: "43. Long Potting - Practice for success",
        channel: "Barry Stark Snooker Coach",
      }
    ),
  },
  {
    id: "routine-black-off-spot",
    category_id: "cat-break-building",
    name: "Black Off The Spot",
    icon: "⚫",
    difficulty: "intermediate",
    summary: "Repeat black-spot pots with controlled cue-ball pace.",
    description: "Useful for grooving potting line and pace into black-pocket routes.",
    setup_instructions: "Keep black on spot and play repeated pots from marked cue-ball positions.",
    steps: ["Play 5 from each cue-ball marker.", "Vary angle gradually.", "Track misses by jaw/line."],
    success_criteria: "Total makes from 25 attempts.",
    improves: ["Black-ball potting", "Pace control", "Cueing precision"],
    scoring_type: "count",
    max_score: 25,
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "lLYEZpMoZz8",
        title: "The best angle on the black!",
        channel: "BartonSnooker",
      },
      {
        id: "86wIb7G6Qqg",
        title: "Why I Missed An Easy Pot.. Explained to try to stop it happening. (Snooker T Practice Routine)",
        channel: "Break Into Snooker",
      }
    ),
  },
  {
    id: "routine-blue-ball-control",
    category_id: "cat-break-building",
    name: "Blue Ball Position Routine",
    icon: "🔷",
    difficulty: "intermediate",
    summary: "Control side-spin and route shape around blue-ball shots.",
    description: "A practical drill for white-ball pathing off blue with controlled side.",
    setup_instructions: "Keep blue on spot and choose 4 cue-ball start positions around baulk and center.",
    steps: ["Play two reps from each position with plain ball.", "Repeat with side spin.", "Compare cue-ball path accuracy."],
    success_criteria: "Route-completion percentage over 16 attempts.",
    improves: ["Blue-ball confidence", "Side-spin judgement", "Route understanding"],
    scoring_type: "percentage",
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "iFNETOzgSts",
        title: "Snooker Blue Ball Common Shots PART 2 - Snooker Lesson",
        channel: "BartonSnooker",
      },
      {
        id: "HYFmkCzJZ7A",
        title: "Snooker Side Spin On The Blue - Snooker Training",
        channel: "BartonSnooker",
      }
    ),
  },
];
