import { Routine, RoutineCategory } from "../types";
import { getYoutubeWatchUrl } from "../utils/youtube";

type VideoMeta = {
  id: string;
  title: string;
  channel: string;
};

const now = new Date().toISOString();

const withYouTube = (primary: VideoMeta, alternate?: VideoMeta) => ({
  youtube_video_id: primary.id,
  youtube_url: getYoutubeWatchUrl(primary.id),
  youtube_title: primary.title,
  youtube_channel: primary.channel,
  youtube_alt_video_id: alternate?.id,
  youtube_alt_url: alternate ? getYoutubeWatchUrl(alternate.id) : undefined,
  youtube_alt_title: alternate?.title,
  youtube_alt_channel: alternate?.channel,
});

export const DEFAULT_CATEGORIES: RoutineCategory[] = [
  {
    id: "cat-basics",
    name: "Fundamentals Library",
    description: "Detailed technique guides on grip, stance, bridge, cue action and aiming. Use them as building blocks, then adapt for your own body and natural cueing style.",
    icon: "🎯",
    color: "#0F766E",
    order_index: 1,
    created_at: now,
  },
  {
    id: "cat-break-building",
    name: "Break Building & Colors",
    description: "Pattern drills and color-control routines for scoring visits.",
    icon: "🔥",
    color: "#B45309",
    order_index: 2,
    created_at: now,
  },
  {
    id: "cat-safety",
    name: "Safety & Escapes",
    description: "Containment, snookers and escape routines for tactical control.",
    icon: "🛡️",
    color: "#1D4ED8",
    order_index: 3,
    created_at: now,
  },
  {
    id: "cat-straight-cueing",
    name: "Cue Delivery & Lines",
    description: "Straight-line cueing, striking quality, and delivery consistency drills.",
    icon: "🎱",
    color: "#334155",
    order_index: 4,
    created_at: now,
  },
  {
    id: "cat-cue-ball-control",
    name: "Cue Ball Control & Spin",
    description: "Stun, screw, topspin and sidespin drills for precise position play.",
    icon: "📈",
    color: "#7C3AED",
    order_index: 5,
    created_at: now,
  },
  {
    id: "cat-long-potting",
    name: "Long Potting & Starters",
    description: "Distance potting and opening-red confidence from match-like positions.",
    icon: "🏆",
    color: "#BE123C",
    order_index: 6,
    created_at: now,
  },
];

export const DEFAULT_ROUTINES: Routine[] = [
  {
    id: "routine-bridge-grip-stance",
    category_id: "cat-basics",
    name: "Stance and Balance Basics",
    icon: "🧍",
    content_type: "guide",
    difficulty: "beginner",
    summary: "Build a stable stance first, because balance and head stillness decide whether your cue can deliver straight.",
    description:
      "Your stance is the platform for every shot. If balance shifts during delivery, the cue path usually shifts with it and you get thin or thick misses, especially under pressure. This guide explains the core principles used by top players, while reminding you that exact foot position can vary by height, flexibility and comfort.",
    setup_instructions:
      "Set up mostly easy straight and slight-angle pots so you can focus on body mechanics. The goal is not hard potting; it is learning a repeatable address position you can trust in match conditions.",
    steps: [
      "Set your feet before you bend down, and feel your weight balanced and supported, not stretched or unstable.",
      "Choose the shot line while standing, then lower onto that line without twisting your shoulders or hips at the last second.",
      "Keep your head and chest quiet through impact and hold the finish long enough to check if you stayed still.",
      "If you feel strain in your lower back, neck or bridge arm, make small comfort adjustments and retest. Comfortable mechanics are easier to repeat.",
    ],
    success_criteria:
      "Over 20-30 shots, your setup should look similar each time, with minimal movement in head and torso. If misses happen, they should be easier to diagnose because your body is no longer changing between shots.",
    improves: ["Shot stability", "Body alignment", "Pressure resilience", "Repeatable setup"],
    scoring_type: "count",
    estimated_duration_minutes: 15,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "olOV1TVMqtI",
        title: "The Stance",
        channel: "Shaun Murphy Snooker",
      },
      {
        id: "pOWMCJLlQxc",
        title: "The SNOOKER SETUP | Important Details",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-pre-shot-routine",
    category_id: "cat-basics",
    name: "Grip Fundamentals",
    icon: "✋",
    content_type: "guide",
    difficulty: "beginner",
    summary: "Build a pressure-aware grip that stays relaxed in feathering but still delivers a committed strike.",
    description:
      "Grip pressure has a huge effect on cue freedom and timing. Too tight and the arm locks, steering the cue and killing smooth acceleration. Too loose and the cue can wobble at transition, especially on power shots. This guide blends classic fundamentals with modern coaching ideas: start with a soft hold, then allow a natural squeeze through impact without strangling the cue.",
    setup_instructions:
      "Use one repeat pot at short and medium distance. Keep the shot constant and only vary grip pressure so you can feel how timing and cue path change.",
    steps: [
      "Start with a light hold in your back fingers and keep forearm/wrist free during feathering.",
      "On delivery, allow a natural tightening only as the cue passes the cue-ball. Do not clamp early.",
      "Test three pressures on the same shot (light, medium, firm) and log which gives the straightest cue path.",
      "On power shots, increase control gradually while still keeping the arm flowing, not rigid.",
    ],
    success_criteria:
      "Across 20-30 reps, your cue action should stay smooth with fewer jabbed deliveries and less accidental side spin. Your best pressure level should feel repeatable, not forced.",
    improves: ["Grip control", "Cue freedom", "Strike timing", "Delivery stability"],
    scoring_type: "count",
    estimated_duration_minutes: 15,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "b3so08CEOAo",
        title: "Snooker Grip Fundamentals",
        channel: "SnookerLab",
      },
      {
        id: "9r4Tllvo8l8",
        title: "Grip Alternative Guide",
        channel: "SnookerLab",
      }
    ),
  },
  {
    id: "routine-bridge-fundamentals",
    category_id: "cat-basics",
    name: "Bridge Fundamentals",
    icon: "🫱",
    content_type: "guide",
    difficulty: "beginner",
    summary: "Learn stable bridge construction, then adapt open, closed and specialty bridges to shot demands.",
    description:
      "A solid bridge is the cue's front rail. If it moves, your tip line moves. This guide covers the most widely taught bridge principles from both traditional coaching and modern online instruction: anchored finger pads, clear cue channel, and shape changes for screw, cushion shots, shots over balls, and rest work.",
    setup_instructions:
      "Use one repeat pot and one along-cushion pot. Practice open bridge, closed bridge, rail bridge, and raised bridge over an object ball while keeping the same cueing rhythm.",
    steps: [
      "Form a standard open bridge: spread fingers, plant finger pads, and create a straight cue groove.",
      "Build a closed bridge for extra cue guidance on power or side shots where stability is harder.",
      "For screw shots, lower bridge height while preserving firmness and a clear cue path.",
      "For cushion, over-ball, and awkward reach shots, adapt shape but protect the same core principle: no bridge wobble through impact.",
    ],
    success_criteria:
      "Across mixed bridge types, your hand remains planted and cue remains centered through delivery. You should feel confident switching bridge style without losing strike quality.",
    improves: ["Bridge stability", "Shot adaptability", "Cue guidance", "Awkward-shot confidence"],
    scoring_type: "count",
    estimated_duration_minutes: 16,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "jgysxTFjULE",
        title: "The Bridge",
        channel: "Shaun Murphy Snooker",
      },
      {
        id: "rxSg2ciaV8A",
        title: "The Perfect Bridge Hand Position",
        channel: "Stephen Hendry's Cue Tips",
      }
    ),
  },
  {
    id: "routine-rest-shot-fundamentals",
    category_id: "cat-basics",
    name: "Alignment and Sighting Basics",
    icon: "👁️",
    content_type: "guide",
    difficulty: "beginner",
    summary: "Train your eyes to choose the line early and stay committed, because late visual changes are a common reason for misses.",
    description:
      "Good sighting links planning and execution. If you get down before deciding the true contact point, your brain tends to make rushed corrections during the cue action. That leads to steering, deceleration and inconsistent potting. This guide teaches a consistent visual process while allowing room for individual differences in dominant eye and address style.",
    setup_instructions:
      "Use straight, half-ball and three-quarter-ball examples. Calling these angles before each shot improves judgement and makes aiming errors easier to classify.",
    steps: [
      "Stand directly behind the shot line and decide the intended contact point before approaching the table.",
      "Step into stance with cue, forearm and intended line connected; avoid walking in from the side and correcting late.",
      "Keep your final visual routine consistent so your trigger point and timing become automatic.",
      "If you miss, label it clearly as thick, thin or pace-related rather than guessing. Honest feedback speeds improvement.",
    ],
    success_criteria:
      "You can call contact thickness before each shot and stay committed to it through delivery. Misses should become more predictable rather than random.",
    improves: ["Aiming clarity", "Line commitment", "Visual routine", "Decision confidence"],
    scoring_type: "percentage",
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "CJHVs0SN4jI",
        title: "A Dummies Guide to Sighting",
        channel: "Shaun Murphy Snooker",
      },
      {
        id: "nSVc5gvvlmc",
        title: "08. Aiming in Snooker - Where should you look?",
        channel: "Barry Stark Snooker Coach",
      }
    ),
  },
  {
    id: "routine-potting-fundamentals",
    category_id: "cat-basics",
    name: "Cueing Action and Potting Basics",
    icon: "🎯",
    content_type: "guide",
    difficulty: "beginner",
    summary: "Develop a repeatable cue action with clear rhythm, pause and follow-through so pressure does not break your timing.",
    description:
      "Cue action is where fundamentals meet the cue ball. Many misses come from rushing the transition, jabbing at impact, or pulling out of the shot too early. This guide builds timing in stages. The exact tempo can be personal, but the principles of smooth acceleration, stable head position and complete follow-through remain essential.",
    setup_instructions:
      "Start with plain-ball pots to confirm strike quality. Add gentle stun and screw only when the basic cue action remains stable and repeatable.",
    steps: [
      "Use the same routine each time: settle, feather, pause, deliver. Consistent timing removes guesswork.",
      "Let the cue accelerate through the cue ball rather than stabbing at it. The cue should finish naturally down the line.",
      "Hold your finish to verify head stillness and cue direction before looking up.",
      "When results dip, return to simple plain-ball shots to rebuild timing before adding spin again.",
    ],
    success_criteria:
      "Across 20+ shots, cue path and finish should look consistent. You should feel less rushed and see fewer misses caused by tension, steering or deceleration.",
    improves: ["Cue timing", "Strike quality", "Potting consistency", "Self-correction"],
    scoring_type: "count",
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "Tr0Olz9qnDo",
        title: "Cue Action and Follow Through",
        channel: "Barry Stark Snooker Coach",
      },
      {
        id: "ilS_YOUpf9s",
        title: "Snooker Aiming Fundamentals",
        channel: "SnookerLab",
      }
    ),
  },
  {
    id: "routine-head-position-fundamentals",
    category_id: "cat-basics",
    name: "Head Position Fundamentals",
    icon: "🧠",
    content_type: "guide",
    difficulty: "beginner",
    summary: "Learn consistent head placement so your eye line and cue line stay connected from setup to strike.",
    description:
      "Head position is one of the biggest hidden causes of inconsistency. If head height, chin distance, or eye alignment changes shot to shot, players misread angles and start steering the cue. This guide teaches a repeatable head position with room for dominant-eye and body-type variations.",
    setup_instructions:
      "Use straight and slight-angle pots. Keep cue-ball and object-ball positions simple so you can focus on head placement, not shot difficulty.",
    steps: [
      "Set your feet and bridge first, then lower head into final position instead of dropping head early.",
      "Bring chin close to cue only as far as comfortable. Avoid forcing your neck lower than your flexibility allows.",
      "Check that eyes feel level and quiet at address, with cue running naturally beneath your visual line.",
      "Hold still after contact and verify whether head moved before or during strike.",
    ],
    success_criteria:
      "Across 20-30 shots, head height and cue-under-chin relationship should look repeatable and misses should become easier to classify.",
    improves: ["Visual consistency", "Cue-line trust", "Aiming stability"],
    scoring_type: "count",
    estimated_duration_minutes: 14,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "EtMpcY6aJEU",
        title: "Head Position and Stability",
        channel: "Barry Stark Snooker Coach",
      },
      {
        id: "1m1Xv-DX7z8",
        title: "Snooker Head Position Alternative",
        channel: "SnookerLab",
      }
    ),
  },
  {
    id: "routine-straight-cueing-fundamentals-guide",
    category_id: "cat-basics",
    name: "Straight Cueing Fundamentals",
    icon: "📏",
    content_type: "guide",
    difficulty: "beginner",
    summary: "Build a cue path that stays true on the line, especially on simple shots where errors are exposed.",
    description:
      "Straight cueing is a base skill that supports aiming, spin control, and pace control. If the cue wanders left/right, even perfect aiming decisions break down. This guide explains how to check cue straightness and remove common steering habits.",
    setup_instructions:
      "Use straight pots and line drills. Begin close and only increase distance when cue path remains clean.",
    steps: [
      "Set up center-ball strikes on straight pots to remove spin variables.",
      "Watch cue travel in and out of the bridge channel during feathers and final delivery.",
      "Track miss pattern: overcut can indicate one side bias; undercut can indicate the opposite.",
      "Use slow-motion video from rear line to confirm whether cue tracks straight through strike.",
    ],
    success_criteria:
      "On a block of straight pots, you should see tighter potting pattern and reduced left/right miss bias.",
    improves: ["Cue-line consistency", "Center-ball contact", "Diagnostic awareness"],
    scoring_type: "count",
    estimated_duration_minutes: 16,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "UZeeYTCXlhI",
        title: "Snooker Mindset For STRAIGHT CUEING",
        channel: "BartonSnooker",
      },
      {
        id: "dQnL-Ot7jXA",
        title: "Snooker Straight Cueing How To Practice",
        channel: "Break from life",
      }
    ),
  },
  {
    id: "routine-cue-ball-control-fundamentals-guide",
    category_id: "cat-basics",
    name: "Cue Ball Control Fundamentals",
    icon: "⚪",
    content_type: "guide",
    difficulty: "beginner",
    summary: "Understand basic cue-ball reactions from simple tip positions before advanced positional play.",
    description:
      "Cue-ball control starts with predictable contact, not complicated patterns. Players improve faster when they master plain-ball, follow, stun, and screw on short controlled shots first. This guide builds those basics in a clear progression.",
    setup_instructions:
      "Use one object-ball position and play repeated shots with clear tip-height intentions: center, above center, below center.",
    steps: [
      "Play plain-ball shots first and observe natural cue-ball path after contact.",
      "Add slight topspin and note how far cue-ball runs through at same cue speed.",
      "Add slight backspin and note return distance at same cue speed.",
      "Record outcomes and keep stroke speed as constant as possible to isolate strike point effects.",
    ],
    success_criteria:
      "You can predict cue-ball finish zones with reasonable accuracy on plain, follow, and screw basics.",
    improves: ["Position awareness", "Tip-height control", "Pace-strike relationship"],
    scoring_type: "count",
    estimated_duration_minutes: 16,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "FdiKPwMl_0M",
        title: "Snooker Cue Ball Control Fundamentals",
        channel: "SnookerLab",
      },
      {
        id: "Zz6Afney-fo",
        title: "Cue Ball Control Alternative Guide",
        channel: "SnookerLab",
      }
    ),
  },
  {
    id: "routine-pre-shot-system-fundamentals",
    category_id: "cat-basics",
    name: "Pre-Shot Routine Fundamentals",
    icon: "🧭",
    content_type: "guide",
    difficulty: "beginner",
    summary: "Create a repeatable pre-shot routine so decision, setup, and delivery happen in a stable sequence.",
    description:
      "A pre-shot routine is the bridge between tactical choice and technical execution. Without structure, players rush hard shots and overthink easy shots. This guide teaches a simple repeatable sequence that can be used in both practice and match play.",
    setup_instructions:
      "Run this guide on easy-to-medium pots first. The goal is consistency of routine, not shot difficulty.",
    steps: [
      "Behind shot: choose objective, contact point, and intended cue-ball route.",
      "Walk-in: approach along shot line and set feet with balance before lowering.",
      "Settle: build bridge, cue on line, and run purposeful feathers.",
      "Commit: pause and deliver without changing decision at last second.",
    ],
    success_criteria:
      "Your routine order stays consistent across different shots, and hesitation or last-second changes reduce over time.",
    improves: ["Decision clarity", "Shot commitment", "Match composure"],
    scoring_type: "count",
    estimated_duration_minutes: 15,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "_JpwKrzVcL4",
        title: "Snooker Pre-Shot Routine Fundamentals",
        channel: "SnookerLab",
      },
      {
        id: "fi8JnUlmhwA",
        title: "Pre-Shot Routine Alternative Guide",
        channel: "SnookerLab",
      }
    ),
  },
  {
    id: "routine-line-up",
    category_id: "cat-break-building",
    name: "The Snooker Line Up",
    icon: "🔥",
    difficulty: "intermediate",
    summary: "Classic 15-red line-up to build break flow and positional discipline.",
    description: "Use a full line of reds through the table center to train break-building patterns with colors on spots.",
    setup_instructions: "Place all colors on spots. Set 15 reds in a center line: 2 below black, 4 between black and pink, 7 between pink and blue, and 2 between blue and brown. Start from a chosen red (often second red behind black).",
    steps: ["Choose a consistent starting red and stick with it for session comparability.", "Pot red-color alternately and keep cue-ball off the cushions where possible.", "If the break ends, reset the line-up and record score or reds cleared before miss."],
    success_criteria: "Track best break and average of 5 visits.",
    improves: ["Break continuity", "Angle management", "Recovery choices"],
    scoring_type: "points",
    max_score: 147,
    estimated_duration_minutes: 30,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "3CKs5pmfss4",
        title: "The Line Up",
        channel: "Shaun Murphy Snooker",
      },
      {
        id: "vv2Wjdf3wl8",
        title: "Snooker Line-Up Tutorial - Snooker Lesson",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-t-routine",
    category_id: "cat-break-building",
    name: "The Snooker T Line Up",
    icon: "📐",
    difficulty: "advanced",
    summary: "Advanced T-shape break-building routine for tight-area cue-ball control.",
    description: "The T Line-Up challenges route planning and short-control potting around the pink/blue lanes.",
    setup_instructions: "Place all colors on spots. Set 15 reds in a T: 5 evenly spaced from pink toward left side rail, 5 from pink toward right side rail, and 5 in a stem between pink and black.",
    steps: ["Start from a chosen red with white between the red group and blue lane.", "Play red-color alternation while keeping cue-ball in or near the T working zone.", "If you miss, reset and track break score or reds remaining to compare sessions."],
    success_criteria: "Count completed T clearances and total successful visits in 30 minutes.",
    improves: ["Pattern planning", "Cue-ball routes", "Discipline"],
    scoring_type: "count",
    estimated_duration_minutes: 30,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "oU3-Cl-N59I",
        title: "Snooker T Practice Routine",
        channel: "Barry Stark Snooker Coach",
      },
      {
        id: "CjBAH5FV4EM",
        title: "Snooker T Exercise - Discipline & Consistency",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-around-colours",
    category_id: "cat-break-building",
    name: "Mastering The Colours",
    icon: "🌈",
    difficulty: "intermediate",
    summary: "Colour-clearance routine for cue-ball touch and planning.",
    description: "Run colors in order while keeping cue-ball paths compact and controlled.",
    setup_instructions: "Use all colors on spots and start cue ball in baulk.",
    steps: ["Call intended cue-ball lane before each color.", "Avoid over-hitting recovery shots.", "Restart sequence on any miss."],
    success_criteria: "Number of full color clearances completed in 20 minutes.",
    improves: ["Touch", "Planning", "Finishing frames"],
    scoring_type: "count",
    max_score: 10,
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "NaWnabDwkEU",
        title: "SNOOKER Colours Clearance | HEADCAM Lesson",
        channel: "BartonSnooker",
      },
      {
        id: "lthLtUJawq0",
        title: "Don't Make These Mistakes When Clearing the Colours",
        channel: "Stephen Hendry's Cue Tips",
      }
    ),
  },
  {
    id: "routine-3-reds-colours",
    category_id: "cat-break-building",
    name: "3 Reds + Colours Clearance",
    icon: "3️⃣",
    difficulty: "intermediate",
    summary: "Short-format break-building with pressure on color choice.",
    description: "A compact routine for players who want realistic break decisions in short blocks.",
    setup_instructions: "Place 3 open reds near black/pink area and keep all colors on spots.",
    steps: ["Pot a red then best available color.", "Preserve easy red access.", "Finish with all colors in sequence."],
    success_criteria: "Count full 3-red clearances from 10 attempts.",
    improves: ["Shot selection", "Mini-break conversion", "End-game focus"],
    scoring_type: "count",
    max_score: 10,
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "VBQPVRbPJnk",
        title: "3 Reds + Colours Clearance Practice Routine",
        channel: "OneFourStephen",
      },
      {
        id: "I5nkzi55xbs",
        title: "Snooker Practice | 3 Reds Break Building | Snooker Lesson",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-break-building-foundations",
    category_id: "cat-break-building",
    name: "Break Building Foundations",
    icon: "📊",
    difficulty: "intermediate",
    summary: "Build break-building habits through repeatable, low-risk patterns.",
    description: "Focus on simple reds, key-ball awareness, and controlled cue-ball travel.",
    setup_instructions: "Open 8-10 reds around pink/black zones.",
    steps: ["Choose easy starter red.", "Play for high-percentage color only.", "Stop and review every breakdown."],
    success_criteria: "Track number of visits above 20 and conversion rate from first red to color control.",
    improves: ["Break conversion", "Risk control", "Frame scoring"],
    scoring_type: "count",
    estimated_duration_minutes: 25,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "48X9fjRbCso",
        title: "6 Steps To Make Your First 100+ Break",
        channel: "Stephen Hendry's Cue Tips",
      },
      {
        id: "D_x1wCMscYo",
        title: "Snooker Beginner Break Building - Snooker Lesson",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-pink-ball-routine",
    category_id: "cat-break-building",
    name: "Shots Around The Pink",
    icon: "🩷",
    difficulty: "advanced",
    summary: "Positional control routine around pink-zone angles.",
    description: "Improve precision around pink and nearby reds while keeping cue-ball paths simple.",
    setup_instructions: "Place two reds near pink with different approach angles.",
    steps: ["Alternate reds each visit.", "Land on ideal pink angle.", "Complete 10 cycles with no positional miss."],
    success_criteria: "Percentage of cycles completed without losing pink position.",
    improves: ["Pink control", "Angle choice", "Cluster navigation"],
    scoring_type: "percentage",
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "CU8Xv_Q2nao",
        title: "Snooker Practice - Two Reds & Pink - Snooker Lesson",
        channel: "BartonSnooker",
      },
      {
        id: "2Paa5oRQQ08",
        title: "Snooker - Pink Cross Practice Routine",
        channel: "Ian Burns Snooker Coaching",
      }
    ),
  },
  {
    id: "routine-baulk-safety",
    category_id: "cat-safety",
    name: "Snooker Safety Shots off Reds",
    icon: "🧱",
    difficulty: "advanced",
    summary: "Touch-based safety drill off reds to lock opponents in baulk.",
    description: "Practice delicate safety contacts that send white to baulk while returning the red toward pink/black traffic.",
    setup_instructions: "Use one red at a time in 6 positions parallel to cushion. First red aligns with black. Keep cue-ball just above black each attempt.",
    steps: ["For each position, contact the red with controlled pace and return white to baulk cushion area.", "Try to finish white behind a baulk color while moving red back toward pink/black.", "Score each shot out of 3: baulk-color cover, baulk-cushion proximity, and red returned safe."],
    success_criteria: "Target 12+ points per 6-ball round and track average over 3 rounds.",
    improves: ["Containment", "Safety pace", "Tactical pressure"],
    scoring_type: "count",
    max_score: 36,
    estimated_duration_minutes: 25,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "Q90ERw5UWfI",
        title: "Safety Play",
        channel: "Shaun Murphy Snooker",
      },
      {
        id: "190nfKvSY4M",
        title: "22. Safety - Practice Exercises",
        channel: "Barry Stark Snooker Coach",
      }
    ),
  },
  {
    id: "routine-escape-science",
    category_id: "cat-safety",
    name: "Escape Science Drill",
    icon: "🧭",
    difficulty: "advanced",
    summary: "Systematic one- and two-cushion escape training.",
    description: "Build dependable escape percentages from common snooker positions.",
    setup_instructions: "Create 10 snookers behind colors and baulk line positions.",
    steps: ["Call contact point before shooting.", "Play legal escape with cue-ball control.", "Record direct-hit and safety outcome."],
    success_criteria: "2 points for legal escape + safe leave, 1 for legal hit only (max 20).",
    improves: ["Escape decision-making", "Swerve/judgment", "Damage limitation"],
    scoring_type: "count",
    max_score: 20,
    estimated_duration_minutes: 25,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube({
      id: "bC1wyWXnp0Y",
      title: "SNOOKER ESCAPE SCIENCE",
      channel: "Cuestars",
    }),
  },
  {
    id: "routine-two-cushion-escape",
    category_id: "cat-safety",
    name: "Two Cushion Escape Drill",
    icon: "2️⃣",
    difficulty: "advanced",
    summary: "Improve reliability on two-cushion escape routes.",
    description: "Teaches reference points and pace for common two-cushion escapes.",
    setup_instructions: "Set 8 snookers where direct path is blocked but two-cushion path exists.",
    steps: ["Pick cushion contact target.", "Play with committed pace.", "Repeat each setup from both sides."],
    success_criteria: "Legal-hit percentage over 24 attempts.",
    improves: ["Cushion maps", "Escape confidence", "Tactical resilience"],
    scoring_type: "percentage",
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "V0XCCgOJPAY",
        title: "Snooker escapes - Mastering 1, 2, 3 cushions escapes (Know How)",
        channel: "Schulte Coach",
      },
      {
        id: "50PzObs5Aos",
        title: "Snooker-two cushions escape",
        channel: "Marek Potter",
      }
    ),
  },
  {
    id: "routine-three-cushion-escape",
    category_id: "cat-safety",
    name: "Three Cushion Escape Drill",
    icon: "3️⃣",
    difficulty: "advanced",
    summary: "Advanced route-finding for deep snookers.",
    description: "Practice three-cushion escapes when low-risk options are limited.",
    setup_instructions: "Set 6 hard snookers where one- and two-cushion routes are blocked.",
    steps: ["Visualize full route first.", "Control pace to avoid leave-ons.", "Grade each attempt for legality and safety."],
    success_criteria: "Track legal-hit percentage and safe-leave percentage separately.",
    improves: ["Route imagination", "Cushion speed control", "Composure"],
    scoring_type: "percentage",
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube({
      id: "A8ymzcMRXIA",
      title: "Snooker escape-Three cushions and more",
      channel: "Marek Potter",
    }),
  },
  {
    id: "routine-straight-cueing-line",
    category_id: "cat-straight-cueing",
    name: "Straight Potting Reds",
    icon: "📍",
    difficulty: "beginner",
    summary: "Straight potting reds routine to expose cueing and aiming drift.",
    description: "A 15-red straight-pot format that quickly reveals recurring overcut or undercut tendencies.",
    setup_instructions: "Place a center red between blue and brown zones, then 7 reds on each side in an even horizontal line. Play cue-ball from along baulk line to straight-pot reds into end pockets.",
    steps: ["Start with center-ball delivery and pot each red as a straight line pot.", "Optional scoring: 2 points potted clean, 1 point jaw rattle, 0 if rail touched first.", "Log miss side and pocket entry line to identify your repeat error pattern."],
    success_criteria: "Track points and miss-pattern consistency over all 15 reds.",
    improves: ["Cue straightness", "Head stillness", "Center-ball confidence"],
    scoring_type: "count",
    max_score: 30,
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "UZeeYTCXlhI",
        title: "Snooker Mindset For STRAIGHT CUEING | Snooker Routine",
        channel: "BartonSnooker",
      },
      {
        id: "dQnL-Ot7jXA",
        title: "Snooker Straight Cueing How To Practice",
        channel: "Break from life",
      }
    ),
  },
  {
    id: "routine-long-blue-straight-cue",
    category_id: "cat-long-potting",
    name: "Potting Long Blues",
    icon: "🔵",
    difficulty: "intermediate",
    summary: "Match-style long-blue confidence builder from progressive distances.",
    description: "Build a reliable long-blue recovery shot to regain table control when position is lost.",
    setup_instructions: "Place blue on spot. Set cue-ball on a straight line to a corner pocket from 2ft, then move to 3ft and 4ft as consistency improves.",
    steps: ["Pot 5-10 long blues into each corner from the current distance.", "Repeat at longer distances while keeping tempo and cueing rhythm constant.", "Record make percentage per pocket and per distance."],
    success_criteria: "Hit your target percentage at one distance before moving further back.",
    improves: ["Long cueing", "Commitment", "Aiming consistency"],
    scoring_type: "percentage",
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube({
      id: "Q-iskgM3P0E",
      title: "Straight Cueing Drill - Long Blue Pot",
      channel: "OneFourStephen",
    }),
  },
  {
    id: "routine-cueing-secret-session",
    category_id: "cat-straight-cueing",
    name: "Loosen Your Snooker Arm",
    icon: "🎥",
    difficulty: "intermediate",
    summary: "Loose-arm warm-up session focused on flow and relaxed delivery.",
    description: "A lower-pressure reds-only session used to free the arm and rebuild smooth cue rhythm.",
    setup_instructions: "Place 15 reds in a center line up the table and pick a starting red near baulk end.",
    steps: ["Pot reds in order or random sequence while keeping cue-ball off cushions where possible.", "Stay loose through grip and arm, prioritizing rhythm over power.", "Reset after a miss for pressure mode, or continue for confidence mode."],
    success_criteria: "Record reds potted per visit and improvement in cueing smoothness across sets.",
    improves: ["Technique reset", "Strike quality", "Self-diagnosis"],
    scoring_type: "count",
    max_score: 30,
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube({
      id: "FEntZrOzjBM",
      title: "SNOOKER CUEING - The Secret To Good Snooker",
      channel: "BartonSnooker",
    }),
  },
  {
    id: "routine-cue-ball-control",
    category_id: "cat-cue-ball-control",
    name: "Cue Ball Control",
    icon: "📈",
    difficulty: "intermediate",
    summary: "Five-tip-position drill for understanding follow, stun, and screw reaction.",
    description: "Learn cue-ball behavior by striking different heights on the vertical center line of the cue-ball.",
    setup_instructions: "Place blue on blue spot. Place cue-ball about 10 inches (250mm) away on a straight line to the middle pocket. Use five tip heights: top, 1cm above center, center, 1cm below center, base.",
    steps: ["Play 5 shots from each tip-height position with a normal smooth stroke.", "Observe whether cue-ball follows, stuns, or screws and by how much.", "Keep arm and grip loose and fully push through the cue-ball."],
    success_criteria: "Log cue-ball finish outcomes for all 25 shots and note repeatability per tip height.",
    improves: ["Spin control", "Pace judgement", "Positional trust"],
    scoring_type: "count",
    max_score: 15,
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "Zz6Afney-fo",
        title: "Stephen Hendry's Number 1 Routine To IMPROVE Cue Ball Control",
        channel: "Stephen Hendry's Cue Tips",
      },
      {
        id: "JA-QGjD7WMA",
        title: "How To Play Top Spin, Stun, & Screw",
        channel: "Stephen Hendry's Cue Tips",
      }
    ),
  },
  {
    id: "routine-stun-run-through",
    category_id: "cat-cue-ball-control",
    name: "Stun Run Through",
    icon: "➡️",
    difficulty: "intermediate",
    summary: "Control stun distance through progressive straight and slight-angle shots.",
    description: "Train consistent stun timing so the cue ball runs through the line without drifting off route.",
    setup_instructions: "Set 5 repeatable red positions from short to medium distance with clear target zones.",
    steps: ["Play each shot with stun-run pace only.", "Hold cueing tempo constant through all 5 positions.", "Track if cue ball lands long, short, or on target."],
    success_criteria: "Count target-zone landings from 20 attempts.",
    improves: ["Stun distance control", "Timing", "Positional consistency"],
    scoring_type: "count",
    max_score: 20,
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "nIv4dLqXM3M",
        title: "Snooker STUN RUN THROUGH | Snooker Tips",
        channel: "BartonSnooker",
      },
      {
        id: "eP8razaeiZA",
        title: "Snooker Stun Run Through - How To Play - Tutorial",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-top-spin-control",
    category_id: "cat-cue-ball-control",
    name: "Top Spin Control",
    icon: "⬆️",
    difficulty: "intermediate",
    summary: "Develop clean topspin contact and reliable follow-through distances.",
    description: "Use this routine to improve forward cue-ball travel while keeping potting line stable.",
    setup_instructions: "Set one object ball and mark 4 follow-through landing bands at increasing distance.",
    steps: ["Play plain-ball follow first, then add controlled topspin.", "Match cue speed to the called landing band.", "Repeat each band 4 times before moving on."],
    success_criteria: "Count successful landings from 16 attempts.",
    improves: ["Topspin contact", "Distance control", "Line retention"],
    scoring_type: "count",
    max_score: 16,
    estimated_duration_minutes: 16,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube({
      id: "l6cTzXMuEzM",
      title: "How To Generate MAXIMUM Top Spin!",
      channel: "BartonSnooker",
    }),
  },
  {
    id: "routine-side-spin-control",
    category_id: "cat-cue-ball-control",
    name: "Side Spin Control",
    icon: "↪️",
    difficulty: "advanced",
    summary: "Build confidence applying side spin without losing cue-ball route control.",
    description: "Practice left/right side selection, aiming compensation, and pace control in match-style patterns.",
    setup_instructions: "Set 6 shots where side spin changes cue-ball path around a blocker or into a target lane.",
    steps: ["Call side and expected cue-ball route before each shot.", "Use controlled cue speed and committed strike.", "Log route accuracy and pot outcome together."],
    success_criteria: "Track route-completion percentage over 18 attempts.",
    improves: ["Side-spin judgment", "Aiming adjustment", "Route shaping"],
    scoring_type: "percentage",
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "Ab-xw7QxLJo",
        title: "How To Aim With Side Correctly",
        channel: "Stephen Hendry's Cue Tips",
      },
      {
        id: "mT1QQxcPjcM",
        title: "Snooker | Ultimate Guide to Side Spin | Tutorial",
        channel: "BartonSnooker",
      }
    ),
  },
  {
    id: "routine-stun-line",
    category_id: "cat-cue-ball-control",
    name: "Mastering Stun Shots",
    icon: "➖",
    difficulty: "intermediate",
    summary: "Train true stun response on straight and slight-angle shots.",
    description: "Use this to stop over-running and improve route precision.",
    setup_instructions: "Set 6 shots with half-ball and three-quarter-ball contacts.",
    steps: ["Play all shots with stun only.", "Check stop line against marker.", "Repeat until line is repeatable."],
    success_criteria: "Land within one-ball tolerance on 12 of 18 attempts.",
    improves: ["Stun timing", "Cue-ball hold", "Route precision"],
    scoring_type: "count",
    max_score: 18,
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "DY0CNNq64Vw",
        title: "Understand and MASTER The STUN SHOT",
        channel: "BartonSnooker",
      },
      {
        id: "Hx0R01_SaO8",
        title: "34. Stun for Control - Improve stun shot play",
        channel: "Barry Stark Snooker Coach",
      }
    ),
  },
  {
    id: "routine-screw-back",
    category_id: "cat-cue-ball-control",
    name: "Screw Back Drill",
    icon: "↩️",
    difficulty: "intermediate",
    summary: "Develop reliable short and medium screw-back distances.",
    description: "A progression drill for low-ball contact and controlled acceleration.",
    setup_instructions: "Set one object ball near middle pocket and mark 3 screw-back distances.",
    steps: ["Play 5 screws to short zone.", "Play 5 to medium zone.", "Play 5 to deep zone."],
    success_criteria: "Count landings inside target windows from 15 attempts.",
    improves: ["Low-ball contact", "Power control", "Recovery play"],
    scoring_type: "count",
    max_score: 15,
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "IS3SJ7jgJSg",
        title: "3 Reasons Why You Can't Screw Back!",
        channel: "BartonSnooker",
      },
      {
        id: "18dR11PwRJY",
        title: "Snooker Spin Screw Back Maximum Back Spin",
        channel: "Break from life",
      }
    ),
  },
  {
    id: "routine-deep-screw",
    category_id: "cat-cue-ball-control",
    name: "Deep Screw Drill",
    icon: "💥",
    difficulty: "advanced",
    summary: "Generate deep screw without losing potting line.",
    description: "Advanced drill for strong draw shots with stable cue delivery.",
    setup_instructions: "Use straight and slight-angle shots at increasing cue-ball distance.",
    steps: ["Play 10 deep screw shots.", "Keep same cue speed profile.", "Log under-hit and over-hit outcomes."],
    success_criteria: "At least 6 of 10 attempts return to target distance band.",
    improves: ["Power generation", "Low-ball precision", "Delivery control"],
    scoring_type: "count",
    max_score: 10,
    estimated_duration_minutes: 15,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube({
      id: "FUMM2Ed4VmU",
      title: "How To Play The Long Deep Screw Back | Snooker",
      channel: "BartonSnooker",
    }),
  },
  {
    id: "routine-long-potting-classic",
    category_id: "cat-long-potting",
    name: "Potting Long Reds",
    icon: "🏆",
    difficulty: "intermediate",
    summary: "Door-opener long-red drill with stun hold for pink position.",
    description: "Practice potting a long red and stopping white where the red started to leave the pink on.",
    setup_instructions: "Place pink on spot. Place a red about 1 foot from pink in line with an end pocket. Place cue-ball on same line, around halfway between blue and baulk colors.",
    steps: ["Strike slightly below center to pot red with stun into end pocket.", "Aim to stop cue-ball on the red's original position for pink access.", "Repeat both sides with 5-10 attempts per side, moving cue-ball further back as control improves."],
    success_criteria: "Track long-red pot % and successful stun-hold % separately.",
    improves: ["Distance potting", "Commitment", "Opening-shot confidence"],
    scoring_type: "percentage",
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "jzi2WbXv-E0",
        title: "The Truth About Long Potting - Snooker",
        channel: "Ian Burns Snooker Coaching",
      },
      {
        id: "h6H4sSf4vZ0",
        title: "43. Long Potting - Practice for success",
        channel: "Barry Stark Snooker Coach",
      }
    ),
  },
  {
    id: "routine-black-off-spot",
    category_id: "cat-break-building",
    name: "Potting The Black Ball",
    icon: "⚫",
    difficulty: "intermediate",
    summary: "Black-spot repetition drill for angle control and position discipline.",
    description: "Repeated black pots sharpen line, touch, and mental composure in tight scoring areas.",
    setup_instructions: "Place black on spot. Start cue-ball halfway between side rail and black at quarter, half, three-quarter, or full-ball angle options.",
    steps: ["Begin with straight blacks into corner pockets and build to tougher angles.", "Keep patterns simple and prioritize white-ball control for the next black.", "Track makes and miss type as position gets wider or drifts to cushions."],
    success_criteria: "Best uninterrupted black run and total makes per 25-ball set.",
    improves: ["Black-ball potting", "Pace control", "Cueing precision"],
    scoring_type: "count",
    max_score: 25,
    estimated_duration_minutes: 18,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "lLYEZpMoZz8",
        title: "The best angle on the black!",
        channel: "BartonSnooker",
      },
      {
        id: "86wIb7G6Qqg",
        title: "Why I Missed An Easy Pot.. Explained to try to stop it happening. (Snooker T Practice Routine)",
        channel: "Break Into Snooker",
      }
    ),
  },
  {
    id: "routine-blue-ball-control",
    category_id: "cat-break-building",
    name: "Potting Multiple Blue Balls",
    icon: "🔷",
    difficulty: "intermediate",
    summary: "Blue-chain break drill when pink/black are tied up.",
    description: "Practice controlling angle on blue to keep opening reds around the blue zone.",
    setup_instructions: "Place all colors on spots. Set 3 reds either side of blue spot in line between brown and pink lanes (6 total to start).",
    steps: ["Start with a red to blue pattern and aim to stay on the correct side of blue.", "Use fine pace so white travels minimal distance between shots.", "When you clear 6 reds consistently, add extra reds to widen the challenge."],
    success_criteria: "Track full-clear count and red-to-blue conversion rate per set.",
    improves: ["Blue-ball confidence", "Side-spin judgement", "Route understanding"],
    scoring_type: "percentage",
    estimated_duration_minutes: 20,
    is_system_routine: true,
    created_at: now,
    updated_at: now,
    ...withYouTube(
      {
        id: "iFNETOzgSts",
        title: "Snooker Blue Ball Common Shots PART 2 - Snooker Lesson",
        channel: "BartonSnooker",
      },
      {
        id: "HYFmkCzJZ7A",
        title: "Snooker Side Spin On The Blue - Snooker Training",
        channel: "BartonSnooker",
      }
    ),
  },
];
