// Builds the 1200x630 link preview (public/og.jpg) from the site's own colours and a screenshot.
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const W = 1200;
const H = 630;
const shot = path.resolve("public/screens/dashboard.png");
const out = path.resolve("public/og.jpg");

const phoneWidth = 268;
const phoneHeight = Math.round((phoneWidth * 2622) / 1206);

const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#0f3326"/>
      <stop offset="100%" stop-color="#081c15"/>
    </linearGradient>
    <radialGradient id="glow" cx="78%" cy="18%" r="60%">
      <stop offset="0%" stop-color="#2fb37f" stop-opacity="0.32"/>
      <stop offset="100%" stop-color="#2fb37f" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="red" cx="34%" cy="30%" r="70%">
      <stop offset="0%" stop-color="#ff6b6b"/><stop offset="48%" stop-color="#c8102e"/><stop offset="100%" stop-color="#5c0714"/>
    </radialGradient>
  </defs>
  <rect width="${W}" height="${H}" fill="url(#bg)"/>
  <rect width="${W}" height="${H}" fill="url(#glow)"/>
  <circle cx="86" cy="96" r="13" fill="url(#red)"/>
  <text x="112" y="107" font-family="Segoe UI, Arial, sans-serif" font-size="30" font-weight="700" fill="#f4f1e8" letter-spacing="1">SNOOKERED</text>
  <text x="84" y="250" font-family="Segoe UI, Arial, sans-serif" font-size="76" font-weight="800" fill="#f4f1e8">Your snooker,</text>
  <text x="84" y="336" font-family="Segoe UI, Arial, sans-serif" font-size="76" font-weight="800" fill="#3ccb90">on the scoreboard.</text>
  <text x="84" y="410" font-family="Segoe UI, Arial, sans-serif" font-size="27" fill="#a9bdb4">Scoring · practice routines · AI coach · AR · your club</text>
  <rect x="84" y="470" width="300" height="62" rx="31" fill="#f4f1e8"/>
  <text x="234" y="509" text-anchor="middle" font-family="Segoe UI, Arial, sans-serif" font-size="24" font-weight="700" fill="#0c2a20">Coming soon to iPhone</text>
</svg>`;

// The phone peeks in from the bottom right, cropped to its top half.
const visible = 470;
const phone = await sharp(shot)
  .resize(phoneWidth, phoneHeight)
  .extract({ left: 0, top: 0, width: phoneWidth, height: visible })
  .composite([
    {
      input: Buffer.from(
        `<svg width="${phoneWidth}" height="${visible}"><rect width="${phoneWidth}" height="${visible + 40}" rx="30" ry="30" fill="#fff"/></svg>`
      ),
      blend: "dest-in",
    },
  ])
  .png()
  .toBuffer();

await mkdir(path.dirname(out), { recursive: true });
await sharp(Buffer.from(svg))
  .composite([{ input: phone, left: 838, top: 150 }])
  .jpeg({ quality: 88 })
  .toFile(out);

await writeFile(path.resolve("public/og.txt"), "og.jpg is generated by scripts/og.mjs during the build.\n");
console.log("og.jpg written");
